'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports NWA.Safetrac.Scanner.Utils

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
'
Namespace NWA.Safetrac.Scanner.WebReferences.NET.ACConfig
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ACConfigSoap", [Namespace]:="http://safetrac.nwa.com/")>  _
    Partial Public Class ACConfig
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = ConfigManager.WS_GetACConfig_AOT
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetACBins", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetACBins(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String) As String
            Dim results() As Object = Me.Invoke("GetACBins", New Object() {DeviceId, Carrier, Flight, FlightDate, Station})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetACBins(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetACBins", New Object() {DeviceId, Carrier, Flight, FlightDate, Station}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetACBins(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetACConfig", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetACConfig(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String) As String
            Dim results() As Object = Me.Invoke("GetACConfig", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetACConfig(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetACConfig", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetACConfig(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetACBinsbyACNum", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetACBinsbyACNum(ByVal DeviceId As String, ByVal AcNum As String, ByVal Station As String) As String
            Dim results() As Object = Me.Invoke("GetACBinsbyACNum", New Object() {DeviceId, AcNum, Station})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetACBinsbyACNum(ByVal DeviceId As String, ByVal AcNum As String, ByVal Station As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetACBinsbyACNum", New Object() {DeviceId, AcNum, Station}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetACBinsbyACNum(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
