'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports NWA.Safetrac.Scanner.Utils

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
'
Namespace NWA.Safetrac.Scanner.WebReferences.NET.DeviceAdmin
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_Device_AdminSoap", [Namespace]:="http://safetrac.nwa.com/")>  _
    Partial Public Class WS_Device_Admin
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = ConfigManager.WS_Device_Admin_AOT
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetAllPWSSettings", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetAllPWSSettings(ByVal ComputerName As String) As String
            Dim results() As Object = Me.Invoke("GetAllPWSSettings", New Object() {ComputerName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetAllPWSSettings(ByVal ComputerName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllPWSSettings", New Object() {ComputerName}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAllPWSSettings(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/CheckSoftwareVersion", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function CheckSoftwareVersion(ByVal Station As String, ByVal AppName As String, ByVal Version As String) As String
            Dim results() As Object = Me.Invoke("CheckSoftwareVersion", New Object() {Station, AppName, Version})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCheckSoftwareVersion(ByVal Station As String, ByVal AppName As String, ByVal Version As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CheckSoftwareVersion", New Object() {Station, AppName, Version}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCheckSoftwareVersion(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetLANSettings", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetLANSettings(ByVal SerialNumber As String) As String
            Dim results() As Object = Me.Invoke("GetLANSettings", New Object() {SerialNumber})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetLANSettings(ByVal SerialNumber As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLANSettings", New Object() {SerialNumber}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetLANSettings(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/UpgradeSoftwareNow", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function UpgradeSoftwareNow(ByVal Station As String, ByVal AppName As String, ByVal RequestedVersion As String, ByVal IPAddress As String) As String
            Dim results() As Object = Me.Invoke("UpgradeSoftwareNow", New Object() {Station, AppName, RequestedVersion, IPAddress})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginUpgradeSoftwareNow(ByVal Station As String, ByVal AppName As String, ByVal RequestedVersion As String, ByVal IPAddress As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpgradeSoftwareNow", New Object() {Station, AppName, RequestedVersion, IPAddress}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndUpgradeSoftwareNow(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetSoftwareList", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetSoftwareList(ByVal Station As String, ByVal AppName As String, ByVal NewVersion As String) As String
            Dim results() As Object = Me.Invoke("GetSoftwareList", New Object() {Station, AppName, NewVersion})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSoftwareList(ByVal Station As String, ByVal AppName As String, ByVal NewVersion As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSoftwareList", New Object() {Station, AppName, NewVersion}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSoftwareList(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
