'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace NWA.Safetrac.Scanner.UI
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Class DisplayMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DisplayMessages", GetType(DisplayMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items Added.
        '''</summary>
        Friend Shared ReadOnly Property AddLateBag() As String
            Get
                Return ResourceManager.GetString("AddLateBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find aircraft registration for Flight &lt;Flight ID&gt;.
        '''</summary>
        Friend Shared ReadOnly Property AircraftRegistrationNoFound() As String
            Get
                Return ResourceManager.GetString("AircraftRegistrationNoFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert Error.
        '''</summary>
        Friend Shared ReadOnly Property AlertError() As String
            Get
                Return ResourceManager.GetString("AlertError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Loaded.
        '''</summary>
        Friend Shared ReadOnly Property AlreadyLoaded() As String
            Get
                Return ResourceManager.GetString("AlreadyLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Registrd.
        '''</summary>
        Friend Shared ReadOnly Property AlreadyRegistered() As String
            Get
                Return ResourceManager.GetString("AlreadyRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already Unloaded.
        '''</summary>
        Friend Shared ReadOnly Property AlreadyUnloaded() As String
            Get
                Return ResourceManager.GetString("AlreadyUnloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Animal.
        '''</summary>
        Friend Shared ReadOnly Property Animal() As String
            Get
                Return ResourceManager.GetString("Animal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unload Bags -&gt; CH.
        '''</summary>
        Friend Shared ReadOnly Property BagstoUnload() As String
            Get
                Return ResourceManager.GetString("BagstoUnload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bag Tag Located.
        '''</summary>
        Friend Shared ReadOnly Property BagTagLocated() As String
            Get
                Return ResourceManager.GetString("BagTagLocated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bag Tag on Alert.
        '''</summary>
        Friend Shared ReadOnly Property BagTagonAlert() As String
            Get
                Return ResourceManager.GetString("BagTagonAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ** Unloaded **.
        '''</summary>
        Friend Shared ReadOnly Property BagUnloaded() As String
            Get
                Return ResourceManager.GetString("BagUnloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Barcode Read Err.
        '''</summary>
        Friend Shared ReadOnly Property BarcodeError() As String
            Get
                Return ResourceManager.GetString("BarcodeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bin Cap Exceeded.
        '''</summary>
        Friend Shared ReadOnly Property BinCapacityExceeded() As String
            Get
                Return ResourceManager.GetString("BinCapacityExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Cancelled.
        '''</summary>
        Friend Shared ReadOnly Property CancelLoadofBagonAlert() As String
            Get
                Return ResourceManager.GetString("CancelLoadofBagonAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge Cancelled.
        '''</summary>
        Friend Shared ReadOnly Property CancelMerge() As String
            Get
                Return ResourceManager.GetString("CancelMerge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cardinal Down.
        '''</summary>
        Friend Shared ReadOnly Property CardinalDown() As String
            Get
                Return ResourceManager.GetString("CardinalDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargo Not Done.
        '''</summary>
        Friend Shared ReadOnly Property CargoNotDone() As String
            Get
                Return ResourceManager.GetString("CargoNotDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cart Only.
        '''</summary>
        Friend Shared ReadOnly Property CartOnly() As String
            Get
                Return ResourceManager.GetString("CartOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERR- Cart Pos.
        '''</summary>
        Friend Shared ReadOnly Property CartPositioned() As String
            Get
                Return ResourceManager.GetString("CartPositioned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cant Pos Carts.
        '''</summary>
        Friend Shared ReadOnly Property CartsNotAllowed() As String
            Get
                Return ResourceManager.GetString("CartsNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for Software Updates.
        '''</summary>
        Friend Shared ReadOnly Property CheckingUpdates() As String
            Get
                Return ResourceManager.GetString("CheckingUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet Already Reg.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSheetAlreadyRegistered() As String
            Get
                Return ResourceManager.GetString("ContainerSheetAlreadyRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet Created.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSheetCreated() As String
            Get
                Return ResourceManager.GetString("ContainerSheetCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet In Use.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSheetinUse() As String
            Get
                Return ResourceManager.GetString("ContainerSheetinUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet Not Regd” or “Cont Sheet Not Regd.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSheetNotRegistered() As String
            Get
                Return ResourceManager.GetString("ContainerSheetNotRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet / ULD In Use” or “ULD is In Use.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSheetorULDinUse() As String
            Get
                Return ResourceManager.GetString("ContainerSheetorULDinUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registered OK.
        '''</summary>
        Friend Shared ReadOnly Property ContainerSuccessfullyRegistered() As String
            Get
                Return ResourceManager.GetString("ContainerSuccessfullyRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Damaged Bag Input.
        '''</summary>
        Friend Shared ReadOnly Property DamagedBag() As String
            Get
                Return ResourceManager.GetString("DamagedBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Error.
        '''</summary>
        Friend Shared ReadOnly Property DatabaseError() As String
            Get
                Return ResourceManager.GetString("DatabaseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dupe Containers – Verify.
        '''</summary>
        Friend Shared ReadOnly Property DupeContainers() As String
            Get
                Return ResourceManager.GetString("DupeContainers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dupe Tag(s) Found.
        '''</summary>
        Friend Shared ReadOnly Property DuplicateBagTag() As String
            Get
                Return ResourceManager.GetString("DuplicateBagTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dupe Tag(s) Found.
        '''</summary>
        Friend Shared ReadOnly Property DuplicateBagTagsFound() As String
            Get
                Return ResourceManager.GetString("DuplicateBagTagsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empty Container.
        '''</summary>
        Friend Shared ReadOnly Property EmptyContainer() As String
            Get
                Return ResourceManager.GetString("EmptyContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Items Loaded.
        '''</summary>
        Friend Shared ReadOnly Property EmptyHold() As String
            Get
                Return ResourceManager.GetString("EmptyHold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expedite this Bag? Press Y or N….
        '''</summary>
        Friend Shared ReadOnly Property ExpediteBag() As String
            Get
                Return ResourceManager.GetString("ExpediteBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expedite this AWB? Press Y or N….
        '''</summary>
        Friend Shared ReadOnly Property ExpediteFreight() As String
            Get
                Return ResourceManager.GetString("ExpediteFreight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Error.
        '''</summary>
        Friend Shared ReadOnly Property FileError() As String
            Get
                Return ResourceManager.GetString("FileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flight Closed Out.
        '''</summary>
        Friend Shared ReadOnly Property FlightClosed() As String
            Get
                Return ResourceManager.GetString("FlightClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flight Departed.
        '''</summary>
        Friend Shared ReadOnly Property FlightDeparted() As String
            Get
                Return ResourceManager.GetString("FlightDeparted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargo Unloaded.
        '''</summary>
        Friend Shared ReadOnly Property FreightUnloaded() As String
            Get
                Return ResourceManager.GetString("FreightUnloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid AWB.
        '''</summary>
        Friend Shared ReadOnly Property InvalidAWB() As String
            Get
                Return ResourceManager.GetString("InvalidAWB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Tag FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidBagTagFormat() As String
            Get
                Return ResourceManager.GetString("InvalidBagTagFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Barcode.
        '''</summary>
        Friend Shared ReadOnly Property InvalidBarcode() As String
            Get
                Return ResourceManager.GetString("InvalidBarcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDateFormat() As String
            Get
                Return ResourceManager.GetString("InvalidDateFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Dept.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDeparture() As String
            Get
                Return ResourceManager.GetString("InvalidDeparture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDepartureDate() As String
            Get
                Return ResourceManager.GetString("InvalidDepartureDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Date FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDepartureDateFormat() As String
            Get
                Return ResourceManager.GetString("InvalidDepartureDateFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Dest.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDestination() As String
            Get
                Return ResourceManager.GetString("InvalidDestination", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Dest FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDestinationFormat() As String
            Get
                Return ResourceManager.GetString("InvalidDestinationFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Flight.
        '''</summary>
        Friend Shared ReadOnly Property InvalidFlight() As String
            Get
                Return ResourceManager.GetString("InvalidFlight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Flt FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidFlightFormat() As String
            Get
                Return ResourceManager.GetString("InvalidFlightFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Bin / Bulk.
        '''</summary>
        Friend Shared ReadOnly Property InvalidHold() As String
            Get
                Return ResourceManager.GetString("InvalidHold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Hub Dest.
        '''</summary>
        Friend Shared ReadOnly Property InvalidHubDestination() As String
            Get
                Return ResourceManager.GetString("InvalidHubDestination", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Login.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPassword() As String
            Get
                Return ResourceManager.GetString("InvalidPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Piece Count.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPieceCount() As String
            Get
                Return ResourceManager.GetString("InvalidPieceCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Pcs.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPieces() As String
            Get
                Return ResourceManager.GetString("InvalidPieces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Position.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPosition() As String
            Get
                Return ResourceManager.GetString("InvalidPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Type.
        '''</summary>
        Friend Shared ReadOnly Property InvalidType() As String
            Get
                Return ResourceManager.GetString("InvalidType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid ULD FMT.
        '''</summary>
        Friend Shared ReadOnly Property InvalidULDFormat() As String
            Get
                Return ResourceManager.GetString("InvalidULDFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid ULD / Sheet.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUldOrCartOrContainerSheet() As String
            Get
                Return ResourceManager.GetString("InvalidUldOrCartOrContainerSheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Login.
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserName() As String
            Get
                Return ResourceManager.GetString("InvalidUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Weight.
        '''</summary>
        Friend Shared ReadOnly Property InvalidWeight() As String
            Get
                Return ResourceManager.GetString("InvalidWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items Added.
        '''</summary>
        Friend Shared ReadOnly Property ItemsAdded() As String
            Get
                Return ResourceManager.GetString("ItemsAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Error.
        '''</summary>
        Friend Shared ReadOnly Property LoadError() As String
            Get
                Return ResourceManager.GetString("LoadError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Mail without barcode?.
        '''</summary>
        Friend Shared ReadOnly Property LoadMailwithoutBarcode() As String
            Get
                Return ResourceManager.GetString("LoadMailwithoutBarcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry Cancelled.
        '''</summary>
        Friend Shared ReadOnly Property LoadMailWithoutBarcodeCancelled() As String
            Get
                Return ResourceManager.GetString("LoadMailWithoutBarcodeCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail Already Registered.
        '''</summary>
        Friend Shared ReadOnly Property MailAlreadyRegistered() As String
            Get
                Return ResourceManager.GetString("MailAlreadyRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail Offloaded.
        '''</summary>
        Friend Shared ReadOnly Property MailOffloaded() As String
            Get
                Return ResourceManager.GetString("MailOffloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail Registered.
        '''</summary>
        Friend Shared ReadOnly Property MailRegistered() As String
            Get
                Return ResourceManager.GetString("MailRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Merge from Scanned Barcode.  Is this the From or To Location?.
        '''</summary>
        Friend Shared ReadOnly Property MergeULD_Cart_Bin_Bulk() As String
            Get
                Return ResourceManager.GetString("MergeULD_Cart_Bin_Bulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heavy Bag Input.
        '''</summary>
        Friend Shared ReadOnly Property MultiHeavyBag() As String
            Get
                Return ResourceManager.GetString("MultiHeavyBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Existing config file not found; downloading..
        '''</summary>
        Friend Shared ReadOnly Property NoConfigurationFile() As String
            Get
                Return ResourceManager.GetString("NoConfigurationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Data Found.
        '''</summary>
        Friend Shared ReadOnly Property NoDataFound() As String
            Get
                Return ResourceManager.GetString("NoDataFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Load Auth.
        '''</summary>
        Friend Shared ReadOnly Property NoLoadAuthority() As String
            Get
                Return ResourceManager.GetString("NoLoadAuthority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No loads on Flt.
        '''</summary>
        Friend Shared ReadOnly Property NoLoadsonFlight() As String
            Get
                Return ResourceManager.GetString("NoLoadsonFlight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FLIGHT NOT CONFIGURED.
        '''</summary>
        Friend Shared ReadOnly Property NonConfiguredFlight() As String
            Get
                Return ResourceManager.GetString("NonConfiguredFlight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Non-Std Wgt.
        '''</summary>
        Friend Shared ReadOnly Property NonStandardWeight() As String
            Get
                Return ResourceManager.GetString("NonStandardWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Err: No Pre-Plan.
        '''</summary>
        Friend Shared ReadOnly Property NoPrePlan() As String
            Get
                Return ResourceManager.GetString("NoPrePlan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal Bag Input.
        '''</summary>
        Friend Shared ReadOnly Property NormalBag() As String
            Get
                Return ResourceManager.GetString("NormalBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Mail Barcode.
        '''</summary>
        Friend Shared ReadOnly Property NotaMailBarcode() As String
            Get
                Return ResourceManager.GetString("NotaMailBarcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Loaded.
        '''</summary>
        Friend Shared ReadOnly Property NotLoaded() As String
            Get
                Return ResourceManager.GetString("NotLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No software updates for &lt;Software Name&gt;.
        '''</summary>
        Friend Shared ReadOnly Property NoUpgradeAvailable() As String
            Get
                Return ResourceManager.GetString("NoUpgradeAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *OK To LOAD.
        '''</summary>
        Friend Shared ReadOnly Property OKtoLoad() As String
            Get
                Return ResourceManager.GetString("OKtoLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *OK LOAD Hvy.
        '''</summary>
        Friend Shared ReadOnly Property OKtoLoadHeavy() As String
            Get
                Return ResourceManager.GetString("OKtoLoadHeavy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to *OK LOAD PB.
        '''</summary>
        Friend Shared ReadOnly Property OKtoLoadPlanesideBag() As String
            Get
                Return ResourceManager.GetString("OKtoLoadPlanesideBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PSGR Not Ckd In.
        '''</summary>
        Friend Shared ReadOnly Property PassengerNotCheckedIn() As String
            Get
                Return ResourceManager.GetString("PassengerNotCheckedIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PSGR On Standby.
        '''</summary>
        Friend Shared ReadOnly Property PassengerOnStandby() As String
            Get
                Return ResourceManager.GetString("PassengerOnStandby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Planeside Input.
        '''</summary>
        Friend Shared ReadOnly Property Planeside() As String
            Get
                Return ResourceManager.GetString("Planeside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Login.
        '''</summary>
        Friend Shared ReadOnly Property PleaseLogin() As String
            Get
                Return ResourceManager.GetString("PleaseLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pos In Use.
        '''</summary>
        Friend Shared ReadOnly Property PositionAlreadyUsed() As String
            Get
                Return ResourceManager.GetString("PositionAlreadyUsed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POS Cap Exceeded.
        '''</summary>
        Friend Shared ReadOnly Property PositionCapacityExceeded() As String
            Get
                Return ResourceManager.GetString("PositionCapacityExceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reasonableness Check for IB / MB Baggage.
        '''</summary>
        Friend Shared ReadOnly Property ReasonablenessCheckfor_IB_MB() As String
            Get
                Return ResourceManager.GetString("ReasonablenessCheckfor_IB_MB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reasonableness Check for Total Cargo.
        '''</summary>
        Friend Shared ReadOnly Property ReasonablenessCheckforCargo() As String
            Get
                Return ResourceManager.GetString("ReasonablenessCheckforCargo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reasonableness Check for Domestic Baggage.
        '''</summary>
        Friend Shared ReadOnly Property ReasonablenessCheckforDomesticBags() As String
            Get
                Return ResourceManager.GetString("ReasonablenessCheckforDomesticBags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register ULD First.
        '''</summary>
        Friend Shared ReadOnly Property RegisterULDFirst() As String
            Get
                Return ResourceManager.GetString("RegisterULDFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert Removed.
        '''</summary>
        Friend Shared ReadOnly Property RemoveAlert() As String
            Get
                Return ResourceManager.GetString("RemoveAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert Removed.
        '''</summary>
        Friend Shared ReadOnly Property RemoveBagAlert() As String
            Get
                Return ResourceManager.GetString("RemoveBagAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrieving Bag Alert Data.  Please Wait….
        '''</summary>
        Friend Shared ReadOnly Property RetrievingBagAlertData() As String
            Get
                Return ResourceManager.GetString("RetrievingBagAlertData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrieving Data.  Please Wait….
        '''</summary>
        Friend Shared ReadOnly Property RetrievingData() As String
            Get
                Return ResourceManager.GetString("RetrievingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retry # &lt;retry seq #&gt; , Connecting to Safetrac….
        '''</summary>
        Friend Shared ReadOnly Property RetryLogin() As String
            Get
                Return ResourceManager.GetString("RetryLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings changed.
        '''</summary>
        Friend Shared ReadOnly Property SaveConfiguration() As String
            Get
                Return ResourceManager.GetString("SaveConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanner Already Running.
        '''</summary>
        Friend Shared ReadOnly Property ScannerAlreadyRunning() As String
            Get
                Return ResourceManager.GetString("ScannerAlreadyRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan Sheet First.
        '''</summary>
        Friend Shared ReadOnly Property ScanSheetFirst() As String
            Get
                Return ResourceManager.GetString("ScanSheetFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alert Set.
        '''</summary>
        Friend Shared ReadOnly Property SetBagAlert() As String
            Get
                Return ResourceManager.GetString("SetBagAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sheet Redefined.
        '''</summary>
        Friend Shared ReadOnly Property SheetRedefined() As String
            Get
                Return ResourceManager.GetString("SheetRedefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heavy Bag Input.
        '''</summary>
        Friend Shared ReadOnly Property SingleHeavyBag() As String
            Get
                Return ResourceManager.GetString("SingleHeavyBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Wait…Setting up Scanner App.
        '''</summary>
        Friend Shared ReadOnly Property StartMessage() As String
            Get
                Return ResourceManager.GetString("StartMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrieving Bag Tag alert data.  Please Wait….
        '''</summary>
        Friend Shared ReadOnly Property StatusMessageBagAlert() As String
            Get
                Return ResourceManager.GetString("StatusMessageBagAlert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD Already Reg.
        '''</summary>
        Friend Shared ReadOnly Property ULDAlreadyRegistered() As String
            Get
                Return ResourceManager.GetString("ULDAlreadyRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD is closed.
        '''</summary>
        Friend Shared ReadOnly Property ULDClosed() As String
            Get
                Return ResourceManager.GetString("ULDClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD Located.
        '''</summary>
        Friend Shared ReadOnly Property ULDFound() As String
            Get
                Return ResourceManager.GetString("ULDFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD In Use.
        '''</summary>
        Friend Shared ReadOnly Property ULDinUse() As String
            Get
                Return ResourceManager.GetString("ULDinUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD Not Reg’d.
        '''</summary>
        Friend Shared ReadOnly Property ULDisnotyetRegistered() As String
            Get
                Return ResourceManager.GetString("ULDisnotyetRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD OK To Use.
        '''</summary>
        Friend Shared ReadOnly Property ULDisOKtoUse() As String
            Get
                Return ResourceManager.GetString("ULDisOKtoUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown AWB.
        '''</summary>
        Friend Shared ReadOnly Property UnknownAWB() As String
            Get
                Return ResourceManager.GetString("UnknownAWB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Bag Tag.
        '''</summary>
        Friend Shared ReadOnly Property UnknownBag() As String
            Get
                Return ResourceManager.GetString("UnknownBag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown ULD.
        '''</summary>
        Friend Shared ReadOnly Property UnknownContainer() As String
            Get
                Return ResourceManager.GetString("UnknownContainer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Sheet” or “UNK Cont Sheet.
        '''</summary>
        Friend Shared ReadOnly Property UnknownContainerSheet() As String
            Get
                Return ResourceManager.GetString("UnknownContainerSheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNKNOWN ERROR.
        '''</summary>
        Friend Shared ReadOnly Property UnknownError() As String
            Get
                Return ResourceManager.GetString("UnknownError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Flight.
        '''</summary>
        Friend Shared ReadOnly Property UnknownFlight() As String
            Get
                Return ResourceManager.GetString("UnknownFlight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Hagent.
        '''</summary>
        Friend Shared ReadOnly Property UnknownHandlingAgent() As String
            Get
                Return ResourceManager.GetString("UnknownHandlingAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail Not Found.
        '''</summary>
        Friend Shared ReadOnly Property UnknownMail() As String
            Get
                Return ResourceManager.GetString("UnknownMail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Barcode Not Read.
        '''</summary>
        Friend Shared ReadOnly Property UnknownScan() As String
            Get
                Return ResourceManager.GetString("UnknownScan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Scanner ID.
        '''</summary>
        Friend Shared ReadOnly Property UnknownScanner() As String
            Get
                Return ResourceManager.GetString("UnknownScanner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offload first before reloading.
        '''</summary>
        Friend Shared ReadOnly Property UnloadFreight() As String
            Get
                Return ResourceManager.GetString("UnloadFreight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unload Mail without barcode?.
        '''</summary>
        Friend Shared ReadOnly Property UnloadMailwithoutBarcode() As String
            Get
                Return ResourceManager.GetString("UnloadMailwithoutBarcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upgrade Failure from &lt;Service Name&gt; &lt;error message from service&gt;.
        '''</summary>
        Friend Shared ReadOnly Property UpgradeFailed() As String
            Get
                Return ResourceManager.GetString("UpgradeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error on Cargo updates to Flight &lt;Flight ID&gt;.  Please use manual procedure..
        '''</summary>
        Friend Shared ReadOnly Property UseManualProcedure() As String
            Get
                Return ResourceManager.GetString("UseManualProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No access privilege.
        '''</summary>
        Friend Shared ReadOnly Property UserNotAuthorized() As String
            Get
                Return ResourceManager.GetString("UserNotAuthorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to update these settings?.
        '''</summary>
        Friend Shared ReadOnly Property ViewScannerConfiguration() As String
            Get
                Return ResourceManager.GetString("ViewScannerConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome &lt;First Name&gt; &lt;Last Name&gt;.
        '''</summary>
        Friend Shared ReadOnly Property WelcomeMessage() As String
            Get
                Return ResourceManager.GetString("WelcomeMessage", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
