'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace NWA.Safetrac.Scanner.SyncManager
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Class DBTables
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DBTables", GetType(DBTables).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Aircraft_Config.
        '''</summary>
        Friend Shared ReadOnly Property Aircraft() As String
            Get
                Return ResourceManager.GetString("Aircraft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Airline_Code.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCode() As String
            Get
                Return ResourceManager.GetString("AirlineCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Bag_Tag.
        '''</summary>
        Friend Shared ReadOnly Property Bags() As String
            Get
                Return ResourceManager.GetString("Bags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Error_Code.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCode() As String
            Get
                Return ResourceManager.GetString("ErrorCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Flight_Info.
        '''</summary>
        Friend Shared ReadOnly Property Flight() As String
            Get
                Return ResourceManager.GetString("Flight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Freight.
        '''</summary>
        Friend Shared ReadOnly Property Freight() As String
            Get
                Return ResourceManager.GetString("Freight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Line_Item.
        '''</summary>
        Friend Shared ReadOnly Property LineItem() As String
            Get
                Return ResourceManager.GetString("LineItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Mail.
        '''</summary>
        Friend Shared ReadOnly Property Mail() As String
            Get
                Return ResourceManager.GetString("Mail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Passenger_Config.
        '''</summary>
        Friend Shared ReadOnly Property Passenger() As String
            Get
                Return ResourceManager.GetString("Passenger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Sync_Time.
        '''</summary>
        Friend Shared ReadOnly Property SyncTime() As String
            Get
                Return ResourceManager.GetString("SyncTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Container.
        '''</summary>
        Friend Shared ReadOnly Property ULD() As String
            Get
                Return ResourceManager.GetString("ULD", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
