'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace NWA.Safetrac.Scanner.SyncManager
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Class SqlCETableStructures
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SqlCETableStructures", GetType(SqlCETableStructures).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aircraft.
        '''</summary>
        Friend Shared ReadOnly Property AircraftAlias() As String
            Get
                Return ResourceManager.GetString("AircraftAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AIRCRAFT.
        '''</summary>
        Friend Shared ReadOnly Property AircraftCommodityName() As String
            Get
                Return ResourceManager.GetString("AircraftCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Aircraft_Config(&quot;AC_NOSE_NUM nvarchar(10), POS_NUM nvarchar(2),PLLT_LOC_NUM nvarchar(2), IN_USE_IND nvarchar(1) NOT NULL, PLLT_SLT_CDE nvarchar(2) NOT NULL, MODIFIED_TIME datetime NOT NULL, CONSTRAINT pkAirConfig PRIMARY KEY (AC_NOSE_NUM,POS_NUM,PLLT_LOC_NUM)).
        '''</summary>
        Friend Shared ReadOnly Property AircraftCreateCommand() As String
            Get
                Return ResourceManager.GetString("AircraftCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Aircraft_Config] WHERE (([AC_NOSE_NUM] = @p1) AND ([POS_NUM] = @p2) AND ([PLLT_LOC_NUM] = @p3) AND ([IN_USE_IND] = @p4) AND ([PLLT_SLT_CDE] = @p5) AND ([MODIFIED_TIME] = @p6)).
        '''</summary>
        Friend Shared ReadOnly Property AircraftDeleteCommand() As String
            Get
                Return ResourceManager.GetString("AircraftDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property AircraftDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("AircraftDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index airconfigselectindex on T_Aircraft_Config (MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property AircraftIndexCommand() As String
            Get
                Return ResourceManager.GetString("AircraftIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Aircraft_Config] ([AC_NOSE_NUM], [POS_NUM], [PLLT_LOC_NUM], [IN_USE_IND], [PLLT_SLT_CDE], [MODIFIED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6).
        '''</summary>
        Friend Shared ReadOnly Property AircraftInsertCommand() As String
            Get
                Return ResourceManager.GetString("AircraftInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property AircraftScanApplicable() As String
            Get
                Return ResourceManager.GetString("AircraftScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT AC_NOSE_NUM, POS_NUM, PLLT_LOC_NUM, IN_USE_IND, PLLT_SLT_CDE, convert(nvarchar, MODIFIED_TIME,20) as MODIFIED_TIME  FROM T_Aircraft_Config.
        '''</summary>
        Friend Shared ReadOnly Property AircraftSelectCommand() As String
            Get
                Return ResourceManager.GetString("AircraftSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Aircraft_Config.
        '''</summary>
        Friend Shared ReadOnly Property AircraftTableName() As String
            Get
                Return ResourceManager.GetString("AircraftTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Aircraft_Config] SET [AC_NOSE_NUM] = @p1, [POS_NUM] = @p2, [PLLT_LOC_NUM] = @p3, [IN_USE_IND] = @p4, [PLLT_SLT_CDE] = @p5, [MODIFIED_TIME] = @p6 WHERE (([AC_NOSE_NUM] = @p7) AND ([POS_NUM] = @p8) AND ([PLLT_LOC_NUM] = @p9) AND ([IN_USE_IND] = @p10) AND ([PLLT_SLT_CDE] = @p11) AND ([MODIFIED_TIME] = @p12)).
        '''</summary>
        Friend Shared ReadOnly Property AircraftUpdateCommand() As String
            Get
                Return ResourceManager.GetString("AircraftUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property AircraftUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("AircraftUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property AircraftUploadApplicable() As String
            Get
                Return ResourceManager.GetString("AircraftUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AirlineCode.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeAlias() As String
            Get
                Return ResourceManager.GetString("AirlineCodeAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AIRLINECODE.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeCommodityName() As String
            Get
                Return ResourceManager.GetString("AirlineCodeCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Airline_Code(&quot;AL_CDE nvarchar(3), AL_NME nvarchar(35) NOT NULL, AL_NUM nvarchar(3) NOT NULL, MODIFIED_TIME datetime NOT NULL, CONSTRAINT pkAirCode PRIMARY KEY(AL_CDE)).
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeCreateCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Airline_Code] WHERE (([AL_CDE] = @p1) AND ([AL_NME] = @p2) AND ([AL_NUM] = @p3) AND ([MODIFIED_TIME] = @p4)).
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeDeleteCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("AirlineCodeDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index aircodeselectindex on T_Airline_Code (MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeIndexCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Airline_Code] ([AL_CDE], [AL_NME], [AL_NUM], [MODIFIED_TIME]) VALUES (@p1, @p2, @p3, @p4).
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeInsertCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeScanApplicable() As String
            Get
                Return ResourceManager.GetString("AirlineCodeScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT AL_CDE, AL_NME, AL_NUM, convert(nvarchar, MODIFIED_TIME,20) as MODIFIED_TIME FROM T_Airline_Code.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeSelectCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Airline_Code.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeTableName() As String
            Get
                Return ResourceManager.GetString("AirlineCodeTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Airline_Code] SET [AL_CDE] = @p1, [AL_NME] = @p2, [AL_NUM] = @p3, [MODIFIED_TIME] = @p4 WHERE (([AL_CDE] = @p5) AND ([AL_NME] = @p6) AND ([AL_NUM] = @p7) AND ([MODIFIED_TIME] = @p8)).
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeUpdateCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("AirlineCodeUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property AirlineCodeUploadApplicable() As String
            Get
                Return ResourceManager.GetString("AirlineCodeUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bags.
        '''</summary>
        Friend Shared ReadOnly Property BagsAlias() As String
            Get
                Return ResourceManager.GetString("BagsAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BAGS.
        '''</summary>
        Friend Shared ReadOnly Property BagsCommodityName() As String
            Get
                Return ResourceManager.GetString("BagsCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Bag_Tag(&quot;OP_AL_CDE nvarchar(3), OP_FLT_NUM numeric(4,0), FLT_SCHED_DTM datetime, BAG_ID nvarchar(10), BAG_PSGR_SEQ_NUM numeric(7,0), AP_CDE nvarchar(5) NOT NULL, CNTNR_SEQ_NUM numeric(6) NULL, BAG_TYP_CDE nvarchar(4) NULL, CNTNR_ID nvarchar(10) NULL, BAG_TAG_CRTN_DTM datetime NOT NULL, DEST_AP_CDE nvarchar(5) NOT NULL, BSM_CRTN_DTM datetime NULL, BAG_CRTN_TYP_CDE nvarchar(1) NOT NULL, BSM_DEL_IND nvarchar(1) NOT NULL, LD_AUTH_IND nvarchar(1) NOT NULL, SCRTY_STATS_CDE nvarchar(1) NOT NULL, CBN [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsCreateCommand() As String
            Get
                Return ResourceManager.GetString("BagsCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Bag_Tag] WHERE (([OP_AL_CDE] = @p1) AND ([OP_FLT_NUM] = @p2) AND ([FLT_SCHED_DTM] = @p3) AND ([BAG_ID] = @p4) AND ([BAG_PSGR_SEQ_NUM] = @p5) AND ([AP_CDE] = @p6) AND ((@p7 = 1 AND [CNTNR_SEQ_NUM] IS NULL) OR ([CNTNR_SEQ_NUM] = @p8)) AND ((@p9 = 1 AND [BAG_TYP_CDE] IS NULL) OR ([BAG_TYP_CDE] = @p10)) AND ((@p11 = 1 AND [CNTNR_ID] IS NULL) OR ([CNTNR_ID] = @p12)) AND ([BAG_TAG_CRTN_DTM] = @p13) AND ([DEST_AP_CDE] = @p14) AND ((@p15 = 1 AND [BSM_CRTN_DTM] IS NULL) OR ([BSM_CRTN_DTM] = @p16)) AND [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsDeleteCommand() As String
            Get
                Return ResourceManager.GetString("BagsDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Bag_Tag where exists (select  1  FROM t_bag_tag where tempT_Bag_Tag.OP_AL_CDE = t_bag_tag.OP_AL_CDE AND tempT_Bag_Tag.OP_FLT_NUM = t_bag_tag.OP_FLT_NUM AND tempT_Bag_Tag.FLT_SCHED_DTM = t_bag_tag.FLT_SCHED_DTM AND tempT_Bag_Tag.BAG_ID = t_bag_tag.BAG_ID AND            tempT_Bag_Tag.BAG_PSGR_SEQ_NUM = t_bag_tag.BAG_PSGR_SEQ_NUM ).
        '''</summary>
        Friend Shared ReadOnly Property BagsDeleteNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("BagsDeleteNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Bag_Tag where exists (select  1  FROM t_bag_tag where tempT_Bag_Tag.OP_AL_CDE = t_bag_tag.OP_AL_CDE AND tempT_Bag_Tag.OP_FLT_NUM = t_bag_tag.OP_FLT_NUM AND tempT_Bag_Tag.FLT_SCHED_DTM = t_bag_tag.FLT_SCHED_DTM AND tempT_Bag_Tag.BAG_ID = t_bag_tag.BAG_ID AND           tempT_Bag_Tag.BAG_PSGR_SEQ_NUM = t_bag_tag.BAG_PSGR_SEQ_NUM             AND tempT_Bag_Tag.MODIFIED_TIME &gt; t_bag_tag.MODIFIED_TIME AND (tempT_Bag_Tag.SCANNED_TIME &lt;= t_bag_tag.SCANNED_TIME OR tempT_Bag_Tag.SCANNED_TIME IS NULL) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsDeleteOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("BagsDeleteOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Bag_Tag.
        '''</summary>
        Friend Shared ReadOnly Property BagsDeleteTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("BagsDeleteTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property BagsDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("BagsDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index bagtagselectindex on T_Bag_Tag (SCANNED_TIME, MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property BagsIndexCommand() As String
            Get
                Return ResourceManager.GetString("BagsIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Bag_Tag] ([OP_AL_CDE], [OP_FLT_NUM], [FLT_SCHED_DTM], [BAG_ID], [BAG_PSGR_SEQ_NUM], [AP_CDE], [CNTNR_SEQ_NUM], [BAG_TYP_CDE], [CNTNR_ID], [BAG_TAG_CRTN_DTM], [DEST_AP_CDE], [BSM_CRTN_DTM], [BAG_CRTN_TYP_CDE], [BSM_DEL_IND], [LD_AUTH_IND], [SCRTY_STATS_CDE], [CBN_CL_CDE], [LD_STATS_CDE], [OFLD_IND], [LD_SEQ_NUM], [RLBL_IND], [XPDT_IND], [BAG_WT_LB], [POS_NUM], [DMGD_IND], [TRKG_IND], [SHRT_CONN_FLT_IND], [UPDT_TMS], [MODIFIED_TIME], [SCANNED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsInsertCommand() As String
            Get
                Return ResourceManager.GetString("BagsInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Bag_Tag temp where not exists (select  1  FROM t_bag_tag where TEMP.OP_AL_CDE = t_bag_tag.OP_AL_CDE             AND TEMP.OP_FLT_NUM = t_bag_tag.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = t_bag_tag.FLT_SCHED_DTM AND TEMP.BAG_ID = t_bag_tag.BAG_ID AND             TEMP.BAG_PSGR_SEQ_NUM = t_bag_tag.BAG_PSGR_SEQ_NUM ).
        '''</summary>
        Friend Shared ReadOnly Property BagsInsertNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("BagsInsertNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Bag_Tag temp where exists (select  1  FROM t_bag_tag where TEMP.OP_AL_CDE = t_bag_tag.OP_AL_CDE AND TEMP.OP_FLT_NUM = t_bag_tag.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = t_bag_tag.FLT_SCHED_DTM AND TEMP.BAG_ID = t_bag_tag.BAG_ID AND             TEMP.BAG_PSGR_SEQ_NUM = t_bag_tag.BAG_PSGR_SEQ_NUM AND TEMP.MODIFIED_TIME &gt; t_bag_tag.MODIFIED_TIME AND (TEMP.SCANNED_TIME &lt;= t_bag_tag.SCANNED_TIME OR TEMP.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property BagsInsertOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("BagsInsertOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property BagsScanApplicable() As String
            Get
                Return ResourceManager.GetString("BagsScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, OP_FLT_NUM, convert(nvarchar,FLT_SCHED_DTM,23) as FLT_SCHED_DTM, BAG_ID, BAG_PSGR_SEQ_NUM, AP_CDE, coalesce(CNTNR_SEQ_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_SEQ_NUM, coalesce(BAG_TYP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as BAG_TYP_CDE, coalesce(CNTNR_ID, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_ID, convert(nvarchar, BAG_TAG_CRTN_DTM,20) as BAG_TAG_CRTN_DTM, DEST_AP_CDE, coalesce(convert(nvarchar, BSM_CRTN_DTM,20), &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as BSM_CRTN_DTM, BAG_CRTN_TYP_CDE, BSM_DEL_IND, LD_AUTH_IND, SCRTY_ST [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsSelectCommand() As String
            Get
                Return ResourceManager.GetString("BagsSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, OP_FLT_NUM, FLT_SCHED_DTM, BAG_ID, BAG_PSGR_SEQ_NUM, AP_CDE, BAG_TYP_CDE, BAG_TAG_CRTN_DTM, DEST_AP_CDE, BSM_CRTN_DTM, BAG_CRTN_TYP_CDE, BSM_DEL_IND, LD_AUTH_IND, SCRTY_STATS_CDE, CBN_CL_CDE, LD_STATS_CDE, OFLD_IND, LD_SEQ_NUM, RLBL_IND, XPDT_IND, BAG_WT_LB, DMGD_IND, TRKG_IND, SHRT_CONN_FLT_IND, UPDT_TMS, MODIFIED_TIME FROM T_Bag_Tag.
        '''</summary>
        Friend Shared ReadOnly Property BagsSelectNonOverridingFieldsCommand() As String
            Get
                Return ResourceManager.GetString("BagsSelectNonOverridingFieldsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from tempT_Bag_Tag.
        '''</summary>
        Friend Shared ReadOnly Property BagsSelectTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("BagsSelectTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Bag_Tag where exists (select  1  FROM t_bag_tag where tempT_Bag_Tag.OP_AL_CDE = t_bag_tag.OP_AL_CDE AND tempT_Bag_Tag.OP_FLT_NUM = t_bag_tag.OP_FLT_NUM AND tempT_Bag_Tag.FLT_SCHED_DTM = t_bag_tag.FLT_SCHED_DTM AND tempT_Bag_Tag.BAG_ID = t_bag_tag.BAG_ID AND          tempT_Bag_Tag.BAG_PSGR_SEQ_NUM = t_bag_tag.BAG_PSGR_SEQ_NUM             AND tempT_Bag_Tag.MODIFIED_TIME = t_bag_tag.MODIFIED_TIME             AND ((tempT_Bag_Tag.SCANNED_TIME IS NULL AND t_bag_tag.SCANNED_TIME IS NULL) OR (temp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsSkipRecordsCommand() As String
            Get
                Return ResourceManager.GetString("BagsSkipRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Bag_Tag.
        '''</summary>
        Friend Shared ReadOnly Property BagsTableName() As String
            Get
                Return ResourceManager.GetString("BagsTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Bag_Tag] SET [OP_AL_CDE] = @p1, [OP_FLT_NUM] = @p2, [FLT_SCHED_DTM] = @p3, [BAG_ID] = @p4, [BAG_PSGR_SEQ_NUM] = @p5, [AP_CDE] = @p6, [CNTNR_SEQ_NUM] = @p7, [BAG_TYP_CDE] = @p8, [CNTNR_ID] = @p9, [BAG_TAG_CRTN_DTM] = @p10, [DEST_AP_CDE] = @p11, [BSM_CRTN_DTM] = @p12, [BAG_CRTN_TYP_CDE] = @p13, [BSM_DEL_IND] = @p14, [LD_AUTH_IND] = @p15, [SCRTY_STATS_CDE] = @p16, [CBN_CL_CDE] = @p17, [LD_STATS_CDE] = @p18, [OFLD_IND] = @p19, [LD_SEQ_NUM] = @p20, [RLBL_IND] = @p21, [XPDT_IND] = @p22, [BAG_WT_LB] = @p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BagsUpdateCommand() As String
            Get
                Return ResourceManager.GetString("BagsUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property BagsUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("BagsUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property BagsUploadApplicable() As String
            Get
                Return ResourceManager.GetString("BagsUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ErrorCodes.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeAlias() As String
            Get
                Return ResourceManager.GetString("ErrorCodeAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERRORCODES.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeCommodityName() As String
            Get
                Return ResourceManager.GetString("ErrorCodeCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Error_Code(&quot;CODE nvarchar(10), TYPE nvarchar(10) NOT NULL, DESCRIP nvarchar(250) NOT NULL, SEVERITY_LEVEL nvarchar(2) NOT NULL, ACTION nvarchar(20) NOT NULL, MODIFIED_TIME datetime NOT NULL, CONSTRAINT pkErrCode PRIMARY KEY(CODE)).
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeCreateCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Error_Code] WHERE (([CODE] = @p1) AND ([TYPE] = @p2) AND ([DESCRIP] = @p3) AND ([SEVERITY_LEVEL] = @p4) AND ([ACTION] = @p5) AND ([MODIFIED_TIME] = @p6)).
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeDeleteCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("ErrorCodeDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeIndexCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Error_Code] ([CODE], [TYPE], [DESCRIP], [SEVERITY_LEVEL], [ACTION], [MODIFIED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6).
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeInsertCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeScanApplicable() As String
            Get
                Return ResourceManager.GetString("ErrorCodeScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CODE, TYPE, DESCRIP, SEVERITY_LEVEL, ACTION, convert(nvarchar, MODIFIED_TIME,20) as MODIFIED_TIME FROM T_Error_Code.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeSelectCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Error_Code.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeTableName() As String
            Get
                Return ResourceManager.GetString("ErrorCodeTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Error_Code] SET [CODE] = @p1, [TYPE] = @p2, [DESCRIP] = @p3, [SEVERITY_LEVEL] = @p4, [ACTION] = @p5, [MODIFIED_TIME] = @p6 WHERE (([CODE] = @p7) AND ([TYPE] = @p8) AND ([DESCRIP] = @p9) AND ([SEVERITY_LEVEL] = @p10) AND ([ACTION] = @p11) AND ([MODIFIED_TIME] = @p12)).
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeUpdateCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("ErrorCodeUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCodeUploadApplicable() As String
            Get
                Return ResourceManager.GetString("ErrorCodeUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flight.
        '''</summary>
        Friend Shared ReadOnly Property FlightAlias() As String
            Get
                Return ResourceManager.GetString("FlightAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FLIGHT.
        '''</summary>
        Friend Shared ReadOnly Property FlightCommodityName() As String
            Get
                Return ResourceManager.GetString("FlightCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Flight_Info(&quot;AP_CDE nvarchar(5), OP_AL_CDE nvarchar(3), FLT_SCHED_DTM datetime, OP_FLT_NUM numeric(4,0), ISNEWREQUEST nvarchar(5), ARR_DPTR_CDE nvarchar(1), LEG_SEQ_NUM numeric(2), AC_NOSE_NUM nvarchar(5) NOT NULL, ORIG_DEST_IND nvarchar(1) NOT NULL, PRE_CLOSE nvarchar(1) NOT NULL, IS_CLOSE nvarchar(1) NOT NULL, MODIFIED_TIME datetime NOT NULL, CONSTRAINT pkFltinfo PRIMARY KEY(AP_CDE, OP_AL_CDE, FLT_SCHED_DTM, OP_FLT_NUM,ARR_DPTR_CDE, LEG_SEQ_NUM)).
        '''</summary>
        Friend Shared ReadOnly Property FlightCreateCommand() As String
            Get
                Return ResourceManager.GetString("FlightCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete:DELETE FROM [T_Flight_Info] WHERE (([AP_CDE] = @p1) AND ([OP_AL_CDE] = @p2) AND ([FLT_SCHED_DTM] = @p3) AND ([OP_FLT_NUM] = @p4) AND ((@p5 = 1 AND [ISNEWREQUEST] IS NULL) OR ([ISNEWREQUEST] = @p6)) AND ([ARR_DPTR_CDE] = @p7) AND ([LEG_SEQ_NUM] = @p8) AND ([AC_NOSE_NUM] = @p9) AND ([ORIG_DEST_IND] = @p10) AND ([PRE_CLOSE] = @p11) AND ([IS_CLOSE] = @p12) AND ([MODIFIED_TIME] = @p13)).
        '''</summary>
        Friend Shared ReadOnly Property FlightDeleteCommand() As String
            Get
                Return ResourceManager.GetString("FlightDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property FlightDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("FlightDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index fltinfoselectindex on T_Flight_Info (MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property FlightIndexCommand() As String
            Get
                Return ResourceManager.GetString("FlightIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Flight_Info] ([AP_CDE], [OP_AL_CDE], [FLT_SCHED_DTM], [OP_FLT_NUM], [ISNEWREQUEST], [ARR_DPTR_CDE], [LEG_SEQ_NUM], [AC_NOSE_NUM], [ORIG_DEST_IND], [PRE_CLOSE], [IS_CLOSE], [MODIFIED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12).
        '''</summary>
        Friend Shared ReadOnly Property FlightInsertCommand() As String
            Get
                Return ResourceManager.GetString("FlightInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property FlightScanApplicable() As String
            Get
                Return ResourceManager.GetString("FlightScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT AP_CDE, OP_AL_CDE, FLT_SCHED_DTM, OP_FLT_NUM, ISNEWREQUEST, ARR_DPTR_CDE, LEG_SEQ_NUM, AC_NOSE_NUM, ORIG_DEST_IND, PRE_CLOSE, IS_CLOSE, MODIFIED_TIME FROM T_Flight_Info.
        '''</summary>
        Friend Shared ReadOnly Property FlightSelectCommand() As String
            Get
                Return ResourceManager.GetString("FlightSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Flight_Info.
        '''</summary>
        Friend Shared ReadOnly Property FlightTableName() As String
            Get
                Return ResourceManager.GetString("FlightTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Flight_Info] SET [AP_CDE] = @p1, [OP_AL_CDE] = @p2, [FLT_SCHED_DTM] = @p3, [OP_FLT_NUM] = @p4, [ISNEWREQUEST] = @p5, [ARR_DPTR_CDE] = @p6, [LEG_SEQ_NUM] = @p7, [AC_NOSE_NUM] = @p8, [ORIG_DEST_IND] = @p9, [PRE_CLOSE] = @p10, [IS_CLOSE] = @p11, [MODIFIED_TIME] = @p12 WHERE (([AP_CDE] = @p13) AND ([OP_AL_CDE] = @p14) AND ([FLT_SCHED_DTM] = @p15) AND ([OP_FLT_NUM] = @p16) AND ((@p17 = 1 AND [ISNEWREQUEST] IS NULL) OR ([ISNEWREQUEST] = @p18)) AND ([ARR_DPTR_CDE] = @p19) AND ([LEG_SEQ_NUM] = @p20) AND ( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FlightUpdateCommand() As String
            Get
                Return ResourceManager.GetString("FlightUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property FlightUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("FlightUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property FlightUploadApplicable() As String
            Get
                Return ResourceManager.GetString("FlightUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freight.
        '''</summary>
        Friend Shared ReadOnly Property FreightAlias() As String
            Get
                Return ResourceManager.GetString("FreightAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FREIGHT.
        '''</summary>
        Friend Shared ReadOnly Property FreightCommodityName() As String
            Get
                Return ResourceManager.GetString("FreightCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Freight(&quot;OP_AL_CDE nvarchar(3), AP_CDE nvarchar(5), OP_FLT_NUM numeric(4,0), FLT_SCHED_DTM datetime, ARR_DPTR_CDE nvarchar(1), AWB_NUM nvarchar(18), WF_SCRN_LIN_ITM_NUM numeric(4,0) NULL, CMDTY_TYP_CDE nvarchar(8) NOT NULL, ITM_CNT numeric(4) NOT NULL, ITM_WT_LB numeric(6,1) NOT NULL, AVG_ITM_WT_LB numeric(6,1) NOT NULL, DEST_AP_CDE nvarchar(5) NOT NULL, FNL_DEST_AP_CDE nvarchar(5) NULL, THRU_IND nvarchar(1) NOT NULL, POS_NUM nvarchar(2) NULL, PREV_POS_NUM nvarchar(2) NULL, LOAD_SEQ_NUM numer [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightCreateCommand() As String
            Get
                Return ResourceManager.GetString("FreightCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Freight] WHERE (([OP_AL_CDE] = @p1) AND ([AP_CDE] = @p2) AND ([OP_FLT_NUM] = @p3) AND ([FLT_SCHED_DTM] = @p4) AND ([ARR_DPTR_CDE] = @p5) AND ([AWB_NUM] = @p6) AND ((@p7 = 1 AND [WF_SCRN_LIN_ITM_NUM] IS NULL) OR ([WF_SCRN_LIN_ITM_NUM] = @p8)) AND ([CMDTY_TYP_CDE] = @p9) AND ([ITM_CNT] = @p10) AND ([ITM_WT_LB] = @p11) AND ([AVG_ITM_WT_LB] = @p12) AND ([DEST_AP_CDE] = @p13) AND ((@p14 = 1 AND [FNL_DEST_AP_CDE] IS NULL) OR ([FNL_DEST_AP_CDE] = @p15)) AND ([THRU_IND] = @p16) AND ((@p17 = 1 AND [PO [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightDeleteCommand() As String
            Get
                Return ResourceManager.GetString("FreightDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Freight where exists (select  1  FROM T_Freight where tempT_Freight.OP_AL_CDE = T_Freight.OP_AL_CDE AND tempT_Freight.OP_FLT_NUM = T_Freight.OP_FLT_NUM AND tempT_Freight.FLT_SCHED_DTM = T_Freight.FLT_SCHED_DTM AND tempT_Freight.ARR_DPTR_CDE = T_Freight.ARR_DPTR_CDE AND             tempT_Freight.AWB_NUM = T_Freight.AWB_NUM ).
        '''</summary>
        Friend Shared ReadOnly Property FreightDeleteNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("FreightDeleteNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Freight where exists (select  1  FROM T_Freight where tempT_Freight.OP_AL_CDE = T_Freight.OP_AL_CDE AND tempT_Freight.OP_FLT_NUM = T_Freight.OP_FLT_NUM AND tempT_Freight.FLT_SCHED_DTM = T_Freight.FLT_SCHED_DTM AND tempT_Freight.ARR_DPTR_CDE = T_Freight.ARR_DPTR_CDE AND             tempT_Freight.AWB_NUM = T_Freight.AWB_NUM AND tempT_Freight.MODIFIED_TIME &gt; T_Freight.MODIFIED_TIME AND (tempT_Freight.SCANNED_TIME &lt; T_Freight.SCANNED_TIME OR tempT_Freight.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property FreightDeleteOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("FreightDeleteOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Freight.
        '''</summary>
        Friend Shared ReadOnly Property FreightDeleteTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("FreightDeleteTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property FreightDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("FreightDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index freightselectindex on T_Freight (SCANNED_TIME, MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property FreightIndexCommand() As String
            Get
                Return ResourceManager.GetString("FreightIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Freight] ([OP_AL_CDE], [AP_CDE], [OP_FLT_NUM], [FLT_SCHED_DTM], [ARR_DPTR_CDE], [AWB_NUM], [WF_SCRN_LIN_ITM_NUM], [CMDTY_TYP_CDE], [ITM_CNT], [ITM_WT_LB], [AVG_ITM_WT_LB], [DEST_AP_CDE], [FNL_DEST_AP_CDE], [THRU_IND], [POS_NUM], [PREV_POS_NUM], [LOAD_SEQ_NUM], [LOAD_IND], [SCN_IND], [SCN_DTM], [CNTNR_SEQ_NUM], [XPDT_IND], [DNGR_FRGT_IND], [FRGT_STG_LOC_CDE], [PREV_FRGT_STG_LOC_CDE], [MODIFIED_TIME], [SCANNED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightInsertCommand() As String
            Get
                Return ResourceManager.GetString("FreightInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Freight temp where not exists (select  1  FROM T_Freight where TEMP.OP_AL_CDE = T_Freight.OP_AL_CDE             AND TEMP.OP_FLT_NUM = T_Freight.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = T_Freight.FLT_SCHED_DTM AND TEMP.ARR_DPTR_CDE = T_Freight.ARR_DPTR_CDE AND TEMP.AWB_NUM = T_Freight.AWB_NUM).
        '''</summary>
        Friend Shared ReadOnly Property FreightInsertNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("FreightInsertNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Freight temp where exists (select  1  FROM T_Freight where TEMP.OP_AL_CDE = T_Freight.OP_AL_CDE AND TEMP.OP_FLT_NUM = T_Freight.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = T_Freight.FLT_SCHED_DTM AND TEMP.ARR_DPTR_CDE = T_Freight.ARR_DPTR_CDE AND TEMP.AWB_NUM = T_Freight.AWB_NUM AND TEMP.MODIFIED_TIME &gt; T_Freight.MODIFIED_TIME AND (TEMP.SCANNED_TIME &lt;= T_Freight.SCANNED_TIME OR TEMP.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property FreightInsertOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("FreightInsertOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property FreightScanApplicable() As String
            Get
                Return ResourceManager.GetString("FreightScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, AP_CDE, OP_FLT_NUM, convert(nvarchar,FLT_SCHED_DTM,23) as FLT_SCHED_DTM, ARR_DPTR_CDE, AWB_NUM, coalesce(WF_SCRN_LIN_ITM_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as WF_SCRN_LIN_ITM_NUM, CMDTY_TYP_CDE, ITM_CNT, ITM_WT_LB, AVG_ITM_WT_LB, DEST_AP_CDE, coalesce(FNL_DEST_AP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as FNL_DEST_AP_CDE, THRU_IND, coalesce(POS_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as POS_NUM, coalesce(PREV_POS_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as PREV_POS_NUM, coalesce(LOAD_SEQ_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as LOAD_SEQ_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightSelectCommand() As String
            Get
                Return ResourceManager.GetString("FreightSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, AP_CDE, OP_FLT_NUM, FLT_SCHED_DTM, ARR_DPTR_CDE, AWB_NUM, WF_SCRN_LIN_ITM_NUM, CMDTY_TYP_CDE, ITM_CNT, ITM_WT_LB, AVG_ITM_WT_LB, DEST_AP_CDE, FNL_DEST_AP_CDE, THRU_IND, LOAD_SEQ_NUM, LOAD_IND, SCN_IND, SCN_DTM, CNTNR_SEQ_NUM, XPDT_IND, DNGR_FRGT_IND, FRGT_STG_LOC_CDE, PREV_FRGT_STG_LOC_CDE, MODIFIED_TIME FROM T_Freight.
        '''</summary>
        Friend Shared ReadOnly Property FreightSelectNonOverridingFieldsCommand() As String
            Get
                Return ResourceManager.GetString("FreightSelectNonOverridingFieldsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from tempT_Freight.
        '''</summary>
        Friend Shared ReadOnly Property FreightSelectTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("FreightSelectTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Freight where exists (select  1  FROM T_Freight where tempT_Freight.OP_AL_CDE = T_Freight.OP_AL_CDE AND tempT_Freight.OP_FLT_NUM = T_Freight.OP_FLT_NUM AND tempT_Freight.FLT_SCHED_DTM = T_Freight.FLT_SCHED_DTM AND tempT_Freight.ARR_DPTR_CDE = T_Freight.ARR_DPTR_CDE AND            tempT_Freight.AWB_NUM = T_Freight.AWB_NUM AND tempT_Freight.MODIFIED_TIME = T_Freight.MODIFIED_TIME AND ((tempT_Freight.SCANNED_TIME IS NULL AND T_Freight.SCANNED_TIME IS NULL) OR (tempT_Freight.SCANNED_TIME = T_F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightSkipRecordsCommand() As String
            Get
                Return ResourceManager.GetString("FreightSkipRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Freight.
        '''</summary>
        Friend Shared ReadOnly Property FreightTableName() As String
            Get
                Return ResourceManager.GetString("FreightTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Freight] SET [OP_AL_CDE] = @p1, [AP_CDE] = @p2, [OP_FLT_NUM] = @p3, [FLT_SCHED_DTM] = @p4, [ARR_DPTR_CDE] = @p5, [AWB_NUM] = @p6, [WF_SCRN_LIN_ITM_NUM] = @p7, [CMDTY_TYP_CDE] = @p8, [ITM_CNT] = @p9, [ITM_WT_LB] = @p10, [AVG_ITM_WT_LB] = @p11, [DEST_AP_CDE] = @p12, [FNL_DEST_AP_CDE] = @p13, [THRU_IND] = @p14, [POS_NUM] = @p15, [PREV_POS_NUM] = @p16, [LOAD_SEQ_NUM] = @p17, [LOAD_IND] = @p18, [SCN_IND] = @p19, [SCN_DTM] = @p20, [CNTNR_SEQ_NUM] = @p21, [XPDT_IND] = @p22, [DNGR_FRGT_IND] = @p23, [FRGT_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property FreightUpdateCommand() As String
            Get
                Return ResourceManager.GetString("FreightUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property FreightUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("FreightUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property FreightUploadApplicable() As String
            Get
                Return ResourceManager.GetString("FreightUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LineItem.
        '''</summary>
        Friend Shared ReadOnly Property LineItemAlias() As String
            Get
                Return ResourceManager.GetString("LineItemAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LINEITEM.
        '''</summary>
        Friend Shared ReadOnly Property LineItemCommodityName() As String
            Get
                Return ResourceManager.GetString("LineItemCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Line_Item(&quot;OP_AL_CDE nvarchar(3) NOT NULL, OP_FLT_NUM numeric(4,0), FLT_SCHED_DTM datetime, LIN_ITEM_SEQ_NUM numeric(7) NOT NULL, MSG_LIN_NUM nvarchar(4) NULL, POS_NUM nvarchar(2) NOT NULL, CNTNR_ID nvarchar(10) NULL, CMDTY_TYP_CDE nvarchar(8) NOT NULL, THRU_IND nvarchar(1) NOT NULL, FNL_DEST_AP_CD nvarchar(5) NOT NULL, AOT_CGO_WT_LBS numeric(6,1) NULL, AOT_CGO_PCS_CNT numeric(5) NULL, WF_CGO_WT_LBS numeric(6,1) NULL, WF_CGO_PCS_CNT numeric(5) NULL, SCNR_ID nvarchar(6) NOT NULL, USR_ID nvarch [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LineItemCreateCommand() As String
            Get
                Return ResourceManager.GetString("LineItemCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Line_Item] WHERE (([OP_AL_CDE] = @p1) AND ([OP_FLT_NUM] = @p2) AND ([FLT_SCHED_DTM] = @p3) AND ([LIN_ITEM_SEQ_NUM] = @p4) AND ((@p5 = 1 AND [MSG_LIN_NUM] IS NULL) OR ([MSG_LIN_NUM] = @p6)) AND ([POS_NUM] = @p7) AND ((@p8 = 1 AND [CNTNR_ID] IS NULL) OR ([CNTNR_ID] = @p9)) AND ([CMDTY_TYP_CDE] = @p10) AND ([THRU_IND] = @p11) AND ([FNL_DEST_AP_CD] = @p12) AND ((@p13 = 1 AND [AOT_CGO_WT_LBS] IS NULL) OR ([AOT_CGO_WT_LBS] = @p14)) AND ((@p15 = 1 AND [AOT_CGO_PCS_CNT] IS NULL) OR ([AOT_CGO_PCS_CNT] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LineItemDeleteCommand() As String
            Get
                Return ResourceManager.GetString("LineItemDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Line_Item where exists (select  1  FROM T_Line_Item where AND tempT_Line_Item.OP_FLT_NUM = T_Line_Item.OP_FLT_NUM             AND tempT_Line_Item.FLT_SCHED_DTM = T_Line_Item.FLT_SCHED_DTM).
        '''</summary>
        Friend Shared ReadOnly Property LineItemDeleteNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("LineItemDeleteNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Line_Item where exists (select  1  FROM T_Line_Item where AND tempT_Line_Item.OP_FLT_NUM = T_Line_Item.OP_FLT_NUM             AND tempT_Line_Item.FLT_SCHED_DTM = T_Line_Item.FLT_SCHED_DTM             AND tempT_Line_Item.MODIFIED_TIME &gt; T_Line_Item.MODIFIED_TIME AND (tempT_Line_Item.SCANNED_TIME &lt;= T_Line_Item.SCANNED_TIME OR tempT_Line_Item.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property LineItemDeleteOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemDeleteOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Line_Item.
        '''</summary>
        Friend Shared ReadOnly Property LineItemDeleteTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemDeleteTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property LineItemDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("LineItemDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index lineitemselectindex on T_Line_Item (SCANNED_TIME, MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property LineItemIndexCommand() As String
            Get
                Return ResourceManager.GetString("LineItemIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Line_Item] ([OP_AL_CDE], [OP_FLT_NUM], [FLT_SCHED_DTM], [LIN_ITEM_SEQ_NUM], [MSG_LIN_NUM], [POS_NUM], [CNTNR_ID], [CMDTY_TYP_CDE], [THRU_IND], [FNL_DEST_AP_CD], [AOT_CGO_WT_LBS], [AOT_CGO_PCS_CNT], [WF_CGO_WT_LBS], [WF_CGO_PCS_CNT], [SCNR_ID], [USR_ID], [RMK_TXT], [MODIFIED_TIME], [SCANNED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19).
        '''</summary>
        Friend Shared ReadOnly Property LineItemInsertCommand() As String
            Get
                Return ResourceManager.GetString("LineItemInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Line_Item temp where not exists (select  1  FROM T_Line_Item where TEMP.OP_FLT_NUM = T_Line_Item.OP_FLT_NUM             AND TEMP.FLT_SCHED_DTM = T_Line_Item.FLT_SCHED_DTM).
        '''</summary>
        Friend Shared ReadOnly Property LineItemInsertNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("LineItemInsertNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Line_Item temp where exists (select  1  FROM T_Line_Item where AND TEMP.OP_FLT_NUM = T_Line_Item.OP_FLT_NUM             AND TEMP.FLT_SCHED_DTM = T_Line_Item.FLT_SCHED_DTM AND TEMP.MODIFIED_TIME &gt; T_Line_Item.MODIFIED_TIME AND (TEMP.SCANNED_TIME &lt;= T_Line_Item.SCANNED_TIME OR TEMP.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property LineItemInsertOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemInsertOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property LineItemScanApplicable() As String
            Get
                Return ResourceManager.GetString("LineItemScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, OP_FLT_NUM, convert(nvarchar,FLT_SCHED_DTM,23) as FLT_SCHED_DTM, LIN_ITEM_SEQ_NUM, coalesce(MSG_LIN_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as MSG_LIN_NUM, coalesce(POS_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as POS_NUM, coalesce(CNTNR_ID, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_ID, CMDTY_TYP_CDE, THRU_IND, FNL_DEST_AP_CD, coalesce(AOT_CGO_WT_LBS, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as AOT_CGO_WT_LBS, coalesce(AOT_CGO_PCS_CNT, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as AOT_CGO_PCS_CNT, coalesce(WF_CGO_WT_LBS, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as WF_CGO_WT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LineItemSelectCommand() As String
            Get
                Return ResourceManager.GetString("LineItemSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LineItemSelectNonOverridingFieldsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemSelectNonOverridingFieldsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from tempT_Line_Item.
        '''</summary>
        Friend Shared ReadOnly Property LineItemSelectTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemSelectTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Line_Item where exists (select  1  FROM T_Line_Item where AND tempT_Line_Item.OP_FLT_NUM = T_Line_Item.OP_FLT_NUM             AND tempT_Line_Item.FLT_SCHED_DTM = T_Line_Item.FLT_SCHED_DTM             AND tempT_Line_Item.MODIFIED_TIME = T_Line_Item.MODIFIED_TIME             AND ((tempT_Line_Item.SCANNED_TIME IS NULL AND T_Line_Item.SCANNED_TIME IS NULL) OR (tempT_Line_Item.SCANNED_TIME = T_Line_Item.SCANNED_TIME)             OR (tempT_Line_Item.SCANNED_TIME &lt; T_Line_Item.SCANNED_TIME)       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LineItemSkipRecordsCommand() As String
            Get
                Return ResourceManager.GetString("LineItemSkipRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Line_Item.
        '''</summary>
        Friend Shared ReadOnly Property LineItemTableName() As String
            Get
                Return ResourceManager.GetString("LineItemTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Line_Item] SET [OP_AL_CDE] = @p1, [OP_FLT_NUM] = @p2, [FLT_SCHED_DTM] = @p3, [LIN_ITEM_SEQ_NUM] = @p4, [MSG_LIN_NUM] = @p5, [POS_NUM] = @p6, [CNTNR_ID] = @p7, [CMDTY_TYP_CDE] = @p8, [THRU_IND] = @p9, [FNL_DEST_AP_CD] = @p10, [AOT_CGO_WT_LBS] = @p11, [AOT_CGO_PCS_CNT] = @p12, [WF_CGO_WT_LBS] = @p13, [WF_CGO_PCS_CNT] = @p14, [SCNR_ID] = @p15, [USR_ID] = @p16, [RMK_TXT] = @p17, [MODIFIED_TIME] = @p18, [SCANNED_TIME] = @p19 WHERE (([OP_AL_CDE] = @p20) AND ([OP_FLT_NUM] = @p21) AND ([FLT_SCHED_DTM] = @ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LineItemUpdateCommand() As String
            Get
                Return ResourceManager.GetString("LineItemUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LineItemUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("LineItemUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property LineItemUploadApplicable() As String
            Get
                Return ResourceManager.GetString("LineItemUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mail.
        '''</summary>
        Friend Shared ReadOnly Property MailAlias() As String
            Get
                Return ResourceManager.GetString("MailAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MAIL.
        '''</summary>
        Friend Shared ReadOnly Property MailCommodityName() As String
            Get
                Return ResourceManager.GetString("MailCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Mail(&quot;MAIL_UNIT_SEQ_NUM numeric(7), MAIL_BRCD_ID nvarchar(30) NULL, AP_CDE nvarchar(5) NULL, OP_AL_CDE nvarchar(3) NOT NULL, OP_FLT_NUM numeric(4,0) NULL, FLT_SCHED_DTM datetime NULL, DEST_AP_CDE nvarchar(5) NULL, FNL_DEST_AP_CDE nvarchar(5) NULL, POS_ID nvarchar(2) NULL, CNTNR_SEQ_NUM numeric(6) NULL, LD_SEQ_NUM numeric(4) NULL, CMDTY_TYP_CDE nvarchar(8) NULL, TOT_WT_LB numeric(6,1) NULL, ITM_CNT numeric(5) NULL, MODIFIED_TIME datetime NOT NULL, SCANNED_TIME datetime NOT NULL, CONSTRAINT pkM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MailCreateCommand() As String
            Get
                Return ResourceManager.GetString("MailCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Mail] WHERE (([MAIL_UNIT_SEQ_NUM] = @p1) AND ((@p2 = 1 AND [MAIL_BRCD_ID] IS NULL) OR ([MAIL_BRCD_ID] = @p3)) AND ((@p4 = 1 AND [AP_CDE] IS NULL) OR ([AP_CDE] = @p5)) AND ([OP_AL_CDE] = @p6) AND ((@p7 = 1 AND [OP_FLT_NUM] IS NULL) OR ([OP_FLT_NUM] = @p8)) AND ((@p9 = 1 AND [FLT_SCHED_DTM] IS NULL) OR ([FLT_SCHED_DTM] = @p10)) AND ((@p11 = 1 AND [DEST_AP_CDE] IS NULL) OR ([DEST_AP_CDE] = @p12)) AND ((@p13 = 1 AND [FNL_DEST_AP_CDE] IS NULL) OR ([FNL_DEST_AP_CDE] = @p14)) AND ((@p15 = 1 AND [POS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MailDeleteCommand() As String
            Get
                Return ResourceManager.GetString("MailDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Mail where exists (select  1  FROM T_Mail where tempT_Mail.MAIL_UNIT_SEQ_NUM = T_Mail.MAIL_UNIT_SEQ_NUM).
        '''</summary>
        Friend Shared ReadOnly Property MailDeleteNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("MailDeleteNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Mail where exists (select  1  FROM T_Mail where tempT_Mail.MAIL_UNIT_SEQ_NUM = T_Mail.MAIL_UNIT_SEQ_NUM AND tempT_Mail.MODIFIED_TIME &gt; T_Mail.MODIFIED_TIME AND (tempT_Mail.SCANNED_TIME &lt;= T_Mail.SCANNED_TIME OR tempT_Mail.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property MailDeleteOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("MailDeleteOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Mail.
        '''</summary>
        Friend Shared ReadOnly Property MailDeleteTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("MailDeleteTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property MailDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("MailDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index mailselectindex on T_Mail (SCANNED_TIME, MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property MailIndexCommand() As String
            Get
                Return ResourceManager.GetString("MailIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Mail] ([MAIL_UNIT_SEQ_NUM], [MAIL_BRCD_ID], [AP_CDE], [OP_AL_CDE], [OP_FLT_NUM], [FLT_SCHED_DTM], [DEST_AP_CDE], [FNL_DEST_AP_CDE], [POS_ID], [CNTNR_SEQ_NUM], [LD_SEQ_NUM], [CMDTY_TYP_CDE], [TOT_WT_LB], [ITM_CNT], [MODIFIED_TIME], [SCANNED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16).
        '''</summary>
        Friend Shared ReadOnly Property MailInsertCommand() As String
            Get
                Return ResourceManager.GetString("MailInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Mail temp where not exists (select  1  FROM T_Mail where TEMP.MAIL_UNIT_SEQ_NUM = T_Mail.MAIL_UNIT_SEQ_NUM).
        '''</summary>
        Friend Shared ReadOnly Property MailInsertNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("MailInsertNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Mail temp where exists (select  1  FROM T_Mail where TEMP.MAIL_UNIT_SEQ_NUM = T_Mail.MAIL_UNIT_SEQ_NUM             AND TEMP.MODIFIED_TIME &gt; T_Mail.MODIFIED_TIME AND (TEMP.SCANNED_TIME &lt;= T_Mail.SCANNED_TIME OR TEMP.SCANNED_TIME IS NULL)).
        '''</summary>
        Friend Shared ReadOnly Property MailInsertOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("MailInsertOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property MailScanApplicable() As String
            Get
                Return ResourceManager.GetString("MailScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT MAIL_UNIT_SEQ_NUM, coalesce(MAIL_BRCD_ID, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as MAIL_BRCD_ID, coalesce(AP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as AP_CDE, OP_AL_CDE, coalesce(OP_FLT_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as OP_FLT_NUM, coalesce(convert(nvarchar, FLT_SCHED_DTM,23), &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as as FLT_SCHED_DTM, coalesce(DEST_AP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as DEST_AP_CDE, coalesce(FNL_DEST_AP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as FNL_DEST_AP_CDE, coalesce(POS_ID, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as POS_ID, coalesce(CNTNR_SEQ_NUM,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MailSelectCommand() As String
            Get
                Return ResourceManager.GetString("MailSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT MAIL_UNIT_SEQ_NUM, MAIL_BRCD_ID, AP_CDE, OP_AL_CDE, OP_FLT_NUM, FLT_SCHED_DTM, DEST_AP_CDE, FNL_DEST_AP_CDE, CNTNR_SEQ_NUM, LD_SEQ_NUM, CMDTY_TYP_CDE, TOT_WT_LB, ITM_CNT, MODIFIED_TIME FROM T_Mail.
        '''</summary>
        Friend Shared ReadOnly Property MailSelectNonOverridingFieldsCommand() As String
            Get
                Return ResourceManager.GetString("MailSelectNonOverridingFieldsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from tempT_Mail.
        '''</summary>
        Friend Shared ReadOnly Property MailSelectTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("MailSelectTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Mail where exists (select  1  FROM T_Mail where tempT_Mail.MAIL_UNIT_SEQ_NUM = T_Mail.MAIL_UNIT_SEQ_NUM AND tempT_Mail.MODIFIED_TIME = T_Mail.MODIFIED_TIME AND ((tempT_Mail.SCANNED_TIME IS NULL AND T_Mail.SCANNED_TIME IS NULL)             OR (tempT_Mail.SCANNED_TIME = T_Mail.SCANNED_TIME) OR (tempT_Mail.SCANNED_TIME &lt; T_Mail.SCANNED_TIME) OR (tempT_Mail.SCANNED_TIME IS NULL))).
        '''</summary>
        Friend Shared ReadOnly Property MailSkipRecordsCommand() As String
            Get
                Return ResourceManager.GetString("MailSkipRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Mail.
        '''</summary>
        Friend Shared ReadOnly Property MailTableName() As String
            Get
                Return ResourceManager.GetString("MailTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Mail] SET [MAIL_UNIT_SEQ_NUM] = @p1, [MAIL_BRCD_ID] = @p2, [AP_CDE] = @p3, [OP_AL_CDE] = @p4, [OP_FLT_NUM] = @p5, [FLT_SCHED_DTM] = @p6, [DEST_AP_CDE] = @p7, [FNL_DEST_AP_CDE] = @p8, [POS_ID] = @p9, [CNTNR_SEQ_NUM] = @p10, [LD_SEQ_NUM] = @p11, [CMDTY_TYP_CDE] = @p12, [TOT_WT_LB] = @p13, [ITM_CNT] = @p14, [MODIFIED_TIME] = @p15, [SCANNED_TIME] = @p16 WHERE (([MAIL_UNIT_SEQ_NUM] = @p17) AND ((@p18 = 1 AND [MAIL_BRCD_ID] IS NULL) OR ([MAIL_BRCD_ID] = @p19)) AND ((@p20 = 1 AND [AP_CDE] IS NULL) OR ([A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MailUpdateCommand() As String
            Get
                Return ResourceManager.GetString("MailUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property MailUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("MailUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property MailUploadApplicable() As String
            Get
                Return ResourceManager.GetString("MailUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PASSENGER.
        '''</summary>
        Friend Shared ReadOnly Property PassengerCommodityName() As String
            Get
                Return ResourceManager.GetString("PassengerCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passenger.
        '''</summary>
        Friend Shared ReadOnly Property PassengerConfigAlias() As String
            Get
                Return ResourceManager.GetString("PassengerConfigAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Passenger_Config(&quot;AP_CDE nvarchar(5), BAG_PSGR_SEQ_NUM numeric(7,0), LEG_SEQ_NUM numeric(2), PNR_NUM nvarchar(7) NOT NULL, LST_NME nvarchar(40) NULL, CKIN_IND nvarchar(1) NOT NULL, BRD_IND nvarchar(1) NOT NULL, RERTE_IND nvarchar(1) NOT NULL, STBY_IND nvarchar(1) NOT NULL, OP_AL_CDE nvarchar(3) NOT NULL, OP_FLT_NUM numeric(4,0) NOT NULL, LEG_AP_CDE nvarchar(5) NOT NULL, MODIFIED_TIME datetime NOT NULL, CONSTRAINT pkPassConfig PRIMARY KEY(AP_CDE, BAG_PSGR_SEQ_NUM, LEG_SEQ_NUM)).
        '''</summary>
        Friend Shared ReadOnly Property PassengerCreateCommand() As String
            Get
                Return ResourceManager.GetString("PassengerCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Passenger_Config] WHERE (([AP_CDE] = @p1) AND ([BAG_PSGR_SEQ_NUM] = @p2) AND ([LEG_SEQ_NUM] = @p3) AND ([PNR_NUM] = @p4) AND ((@p5 = 1 AND [LST_NME] IS NULL) OR ([LST_NME] = @p6)) AND ([CKIN_IND] = @p7) AND ([BRD_IND] = @p8) AND ([RERTE_IND] = @p9) AND ([STBY_IND] = @p10) AND ([OP_AL_CDE] = @p11) AND ([OP_FLT_NUM] = @p12) AND ([LEG_AP_CDE] = @p13) AND ([MODIFIED_TIME] = @p14)).
        '''</summary>
        Friend Shared ReadOnly Property PassengerDeleteCommand() As String
            Get
                Return ResourceManager.GetString("PassengerDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property PassengerDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("PassengerDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index passconfigselectindex on T_Passenger_Config (MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property PassengerIndexCommand() As String
            Get
                Return ResourceManager.GetString("PassengerIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Passenger_Config] ([AP_CDE], [BAG_PSGR_SEQ_NUM], [LEG_SEQ_NUM], [PNR_NUM], [LST_NME], [CKIN_IND], [BRD_IND], [RERTE_IND], [STBY_IND], [OP_AL_CDE], [OP_FLT_NUM], [LEG_AP_CDE], [MODIFIED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13).
        '''</summary>
        Friend Shared ReadOnly Property PassengerInsertCommand() As String
            Get
                Return ResourceManager.GetString("PassengerInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property PassengerScanApplicable() As String
            Get
                Return ResourceManager.GetString("PassengerScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT AP_CDE, BAG_PSGR_SEQ_NUM, LEG_SEQ_NUM, LST_NME, CKIN_IND, BRD_IND, RERTE_IND, STBY_IND, OP_AL_CDE, OP_FLT_NUM, LEG_AP_CDE, MODIFIED_TIME FROM T_Passenger_Config.
        '''</summary>
        Friend Shared ReadOnly Property PassengerSelectCommand() As String
            Get
                Return ResourceManager.GetString("PassengerSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Passenger_Config.
        '''</summary>
        Friend Shared ReadOnly Property PassengerTableName() As String
            Get
                Return ResourceManager.GetString("PassengerTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Passenger_Config] SET [AP_CDE] = @p1, [BAG_PSGR_SEQ_NUM] = @p2, [LEG_SEQ_NUM] = @p3, [PNR_NUM] = @p4, [LST_NME] = @p5, [CKIN_IND] = @p6, [BRD_IND] = @p7, [RERTE_IND] = @p8, [STBY_IND] = @p9, [OP_AL_CDE] = @p10, [OP_FLT_NUM] = @p11, [LEG_AP_CDE] = @p12, [MODIFIED_TIME] = @p13 WHERE (([AP_CDE] = @p14) AND ([BAG_PSGR_SEQ_NUM] = @p15) AND ([LEG_SEQ_NUM] = @p16) AND ([PNR_NUM] = @p17) AND ((@p18 = 1 AND [LST_NME] IS NULL) OR ([LST_NME] = @p19)) AND ([CKIN_IND] = @p20) AND ([BRD_IND] = @p21) AND ([RERTE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property PassengerUpdateCommand() As String
            Get
                Return ResourceManager.GetString("PassengerUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property PassengerUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("PassengerUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property PassengerUploadApplicable() As String
            Get
                Return ResourceManager.GetString("PassengerUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SyncTime.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeAlias() As String
            Get
                Return ResourceManager.GetString("SyncTimeAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SYNCTIME.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeCommodityName() As String
            Get
                Return ResourceManager.GetString("SyncTimeCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Sync_Time(&quot;TABLE_NAME nvarchar(40), SYNC_UPLOAD_TIME datetime NULL, SYNC_DOWNLOAD_TIME datetime NULL, CONSTRAINT pkSynTime PRIMARY KEY(TABLE_NAME)).
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeCreateCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeDeleteCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("SyncTimeDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeIndexCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeInsertCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeScanApplicable() As String
            Get
                Return ResourceManager.GetString("SyncTimeScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT TABLE_NAME, SYNC_UPLOAD_TIME, SYNC_DOWNLOAD_TIME FROM T_Sync_Time.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeSelectCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Sync_Time.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeTableName() As String
            Get
                Return ResourceManager.GetString("SyncTimeTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeUpdateCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("SyncTimeUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to False.
        '''</summary>
        Friend Shared ReadOnly Property SyncTimeUploadApplicable() As String
            Get
                Return ResourceManager.GetString("SyncTimeUploadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD.
        '''</summary>
        Friend Shared ReadOnly Property ULDAlias() As String
            Get
                Return ResourceManager.GetString("ULDAlias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ULD.
        '''</summary>
        Friend Shared ReadOnly Property ULDCommodityName() As String
            Get
                Return ResourceManager.GetString("ULDCommodityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE T_Container(&quot;OP_AL_CDE nvarchar(3), AP_CDE nvarchar(5), OP_FLT_NUM numeric(4,0), FLT_SCHED_DTM datetime, ARR_DPTR_CDE nvarchar(1), CNTNR_SEQ_NUM numeric(6), CNTNR_ID nvarchar(10) NULL, CNTNR_TYP_CDE nvarchar(6) NULL, CNTNR_STATS_CDE nvarchar(1) NOT NULL, POS_NUM nvarchar(2) NULL, FLT_DPTR_DTM datetime NOT NULL, FNL_DEST_AP_CDE nvarchar(5) NULL, MODIFIED_TIME datetime NOT NULL, SCANNED_TIME datetime NOT NULL, CONSTRAINT pkContainer PRIMARY KEY(OP_AL_CDE, AP_CDE, OP_FLT_NUM, FLT_SCHED_DTM, ARR_DP [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDCreateCommand() As String
            Get
                Return ResourceManager.GetString("ULDCreateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM [T_Container] WHERE (([OP_AL_CDE] = @p1) AND ([AP_CDE] = @p2) AND ([OP_FLT_NUM] = @p3) AND ([FLT_SCHED_DTM] = @p4) AND ([ARR_DPTR_CDE] = @p5) AND ([CNTNR_SEQ_NUM] = @p6) AND ((@p7 = 1 AND [CNTNR_ID] IS NULL) OR ([CNTNR_ID] = @p8)) AND ((@p9 = 1 AND [CNTNR_TYP_CDE] IS NULL) OR ([CNTNR_TYP_CDE] = @p10)) AND ([CNTNR_STATS_CDE] = @p11) AND ((@p12 = 1 AND [POS_NUM] IS NULL) OR ([POS_NUM] = @p13)) AND ([FLT_DPTR_DTM] = @p14) AND ((@p15 = 1 AND [FNL_DEST_AP_CDE] IS NULL) OR ([FNL_DEST_AP_CDE] = @p16))  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDDeleteCommand() As String
            Get
                Return ResourceManager.GetString("ULDDeleteCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Container where exists (select  1  FROM T_Container where tempT_Container.OP_AL_CDE = T_Container.OP_AL_CDE             AND tempT_Container.AP_CDE = T_Container.AP_CDE AND tempT_Container.OP_FLT_NUM = T_Container.OP_FLT_NUM AND tempT_Container.FLT_SCHED_DTM = T_Container.FLT_SCHED_DTM AND tempT_Container.ARR_DPTR_CDE = T_Container.ARR_DPTR_CDE AND            tempT_Container.CNTNR_SEQ_NUM = T_Container.CNTNR_SEQ_NUM ).
        '''</summary>
        Friend Shared ReadOnly Property ULDDeleteNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("ULDDeleteNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from tempT_Container where exists (select  1  FROM T_Container where tempT_Container.OP_AL_CDE = T_Container.OP_AL_CDE AND tempT_Container.AP_CDE = T_Container.AP_CDE AND tempT_Container.OP_FLT_NUM = T_Container.OP_FLT_NUM AND tempT_Container.FLT_SCHED_DTM = T_Container.FLT_SCHED_DTM AND tempT_Container.ARR_DPTR_CDE = T_Container.ARR_DPTR_CDE AND            tempT_Container.CNTNR_SEQ_NUM = T_Container.CNTNR_SEQ_NUM AND tempT_Container.MODIFIED_TIME &gt; T_Container.MODIFIED_TIME AND (tempT_Container.SCAN [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDDeleteOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("ULDDeleteOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Container.
        '''</summary>
        Friend Shared ReadOnly Property ULDDeleteTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("ULDDeleteTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ULDDownloadApplicable() As String
            Get
                Return ResourceManager.GetString("ULDDownloadApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create index containerselectindex on T_Container (SCANNED_TIME, MODIFIED_TIME).
        '''</summary>
        Friend Shared ReadOnly Property ULDIndexCommand() As String
            Get
                Return ResourceManager.GetString("ULDIndexCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [T_Container] ([OP_AL_CDE], [AP_CDE], [OP_FLT_NUM], [FLT_SCHED_DTM], [ARR_DPTR_CDE], [CNTNR_SEQ_NUM], [CNTNR_ID], [CNTNR_TYP_CDE], [CNTNR_STATS_CDE], [POS_NUM], [FLT_DPTR_DTM], [FNL_DEST_AP_CDE], [MODIFIED_TIME], [SCANNED_TIME]) VALUES (@p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14).
        '''</summary>
        Friend Shared ReadOnly Property ULDInsertCommand() As String
            Get
                Return ResourceManager.GetString("ULDInsertCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.* from tempT_Container temp where not exists (select  1  FROM T_Container where TEMP.OP_AL_CDE = T_Container.OP_AL_CDE            AND TEMP.AP_CDE = T_Container.AP_CDE AND TEMP.OP_FLT_NUM = T_Container.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = T_Container.FLT_SCHED_DTM AND TEMP.ARR_DPTR_CDE = T_Container.ARR_DPTR_CDE AND TEMP.CNTNR_SEQ_NUM = T_Container.CNTNR_SEQ_NUM).
        '''</summary>
        Friend Shared ReadOnly Property ULDInsertNewRecordCommandBlindUpdate() As String
            Get
                Return ResourceManager.GetString("ULDInsertNewRecordCommandBlindUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select temp.OP_AL_CDE, temp.AP_CDE, temp.OP_FLT_NUM, temp.FLT_SCHED_DTM, temp.ARR_DPTR_CDE, temp.CNTNR_SEQ_NUM, temp.CNTNR_TYP_CDE, temp.FLT_DPTR_DTM, temp.FNL_DEST_AP_CDE, temp.MODIFIED_TIME from tempT_Container temp where exists (select  1  FROM T_Container where TEMP.OP_AL_CDE = T_Container.OP_AL_CDE             AND TEMP.AP_CDE = T_Container.AP_CDE AND TEMP.OP_FLT_NUM = T_Container.OP_FLT_NUM AND TEMP.FLT_SCHED_DTM = T_Container.FLT_SCHED_DTM AND TEMP.ARR_DPTR_CDE = T_Container.ARR_DPTR_CDE AND TEMP.CNTN [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDInsertOnlyNewerServerRecordsCommand() As String
            Get
                Return ResourceManager.GetString("ULDInsertOnlyNewerServerRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ULDScanApplicable() As String
            Get
                Return ResourceManager.GetString("ULDScanApplicable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, AP_CDE, OP_FLT_NUM, convert(nvarchar,FLT_SCHED_DTM,23) as FLT_SCHED_DTM, ARR_DPTR_CDE, CNTNR_SEQ_NUM, coalesce(CNTNR_ID, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_ID, coalesce(CNTNR_TYP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_TYP_CDE, coalesce(CNTNR_STATS_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as CNTNR_STATS_CDE, coalesce(POS_NUM, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as POS_NUM, convert(nvarchar, FLT_DPTR_DTM,23) as FLT_DPTR_DTM, coalesce(FNL_DEST_AP_CDE, &apos;&quot; &amp; String.Empty &amp; &quot;&apos;) as FNL_DEST_AP_CDE, convert(nvarchar, MODIFI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDSelectCommand() As String
            Get
                Return ResourceManager.GetString("ULDSelectCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT OP_AL_CDE, AP_CDE, OP_FLT_NUM, FLT_SCHED_DTM, ARR_DPTR_CDE, CNTNR_SEQ_NUM, CNTNR_TYP_CDE, FLT_DPTR_DTM, FNL_DEST_AP_CDE, MODIFIED_TIME FROM T_Container.
        '''</summary>
        Friend Shared ReadOnly Property ULDSelectNonOverridingFieldsCommand() As String
            Get
                Return ResourceManager.GetString("ULDSelectNonOverridingFieldsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from tempT_Container.
        '''</summary>
        Friend Shared ReadOnly Property ULDSelectTempRecordsCommand() As String
            Get
                Return ResourceManager.GetString("ULDSelectTempRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE from tempT_Container where exists (select  1  FROM T_Container where tempT_Container.OP_AL_CDE = T_Container.OP_AL_CDE AND tempT_Container.AP_CDE = T_Container.AP_CDE AND tempT_Container.OP_FLT_NUM = T_Container.OP_FLT_NUM AND tempT_Container.FLT_SCHED_DTM = T_Container.FLT_SCHED_DTM AND tempT_Container.ARR_DPTR_CDE = T_Container.ARR_DPTR_CDE AND            tempT_Container.CNTNR_SEQ_NUM = T_Container.CNTNR_SEQ_NUM AND tempT_Container.MODIFIED_TIME = T_Container.MODIFIED_TIME             AND ((tempT_C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDSkipRecordsCommand() As String
            Get
                Return ResourceManager.GetString("ULDSkipRecordsCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T_Container.
        '''</summary>
        Friend Shared ReadOnly Property ULDTableName() As String
            Get
                Return ResourceManager.GetString("ULDTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [T_Container] SET [OP_AL_CDE] = @p1, [AP_CDE] = @p2, [OP_FLT_NUM] = @p3, [FLT_SCHED_DTM] = @p4, [ARR_DPTR_CDE] = @p5, [CNTNR_SEQ_NUM] = @p6, [CNTNR_ID] = @p7, [CNTNR_TYP_CDE] = @p8, [CNTNR_STATS_CDE] = @p9, [POS_NUM] = @p10, [FLT_DPTR_DTM] = @p11, [FNL_DEST_AP_CDE] = @p12, [MODIFIED_TIME] = @p13, [SCANNED_TIME] = @p14 WHERE (([OP_AL_CDE] = @p15) AND ([AP_CDE] = @p16) AND ([OP_FLT_NUM] = @p17) AND ([FLT_SCHED_DTM] = @p18) AND ([ARR_DPTR_CDE] = @p19) AND ([CNTNR_SEQ_NUM] = @p20) AND ((@p21 = 1 AND [CNT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ULDUpdateCommand() As String
            Get
                Return ResourceManager.GetString("ULDUpdateCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property ULDUpdateNonOverridenCommand() As String
            Get
                Return ResourceManager.GetString("ULDUpdateNonOverridenCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend Shared ReadOnly Property ULDUploadApplicable() As String
            Get
                Return ResourceManager.GetString("ULDUploadApplicable", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
