'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
'
Namespace NWA.Safetrac.Scanner.WebReferences.NET.WriteFDSG
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_WriteFDSGLineItemSoap", [Namespace]:="http://safetrac.nwa.com/")>  _
    Partial Public Class WS_WriteFDSGLineItem
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://bmlabj01.mn.nwa.com/safetrac/webservices/WS_WriteFDSGLineItem_AOT/WS_Write"& _ 
                "FDSGLineItem.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/AddLineFDSG", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function AddLineFDSG(ByVal UserID As String, ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal Position As String, ByVal Commodity As String, ByVal Pieces As String, ByVal SpecialWeight As String, ByVal Dest As String, ByVal FinalDest As String, ByVal Remarks As String, ByVal Container As String, ByVal Weight As String) As String
            Dim results() As Object = Me.Invoke("AddLineFDSG", New Object() {UserID, DeviceId, Carrier, Flight, FlightDate, Station, Position, Commodity, Pieces, SpecialWeight, Dest, FinalDest, Remarks, Container, Weight})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAddLineFDSG( _
                    ByVal UserID As String,  _
                    ByVal DeviceId As String,  _
                    ByVal Carrier As String,  _
                    ByVal Flight As String,  _
                    ByVal FlightDate As String,  _
                    ByVal Station As String,  _
                    ByVal Position As String,  _
                    ByVal Commodity As String,  _
                    ByVal Pieces As String,  _
                    ByVal SpecialWeight As String,  _
                    ByVal Dest As String,  _
                    ByVal FinalDest As String,  _
                    ByVal Remarks As String,  _
                    ByVal Container As String,  _
                    ByVal Weight As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddLineFDSG", New Object() {UserID, DeviceId, Carrier, Flight, FlightDate, Station, Position, Commodity, Pieces, SpecialWeight, Dest, FinalDest, Remarks, Container, Weight}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAddLineFDSG(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/PositionLine", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function PositionLine(ByVal UserID As String, ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal LineNumber As String, ByVal Position As String) As String
            Dim results() As Object = Me.Invoke("PositionLine", New Object() {UserID, DeviceId, Carrier, Flight, FlightDate, Station, LineNumber, Position})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginPositionLine(ByVal UserID As String, ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal LineNumber As String, ByVal Position As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PositionLine", New Object() {UserID, DeviceId, Carrier, Flight, FlightDate, Station, LineNumber, Position}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPositionLine(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/WriteFDSGLineItem", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function WriteFDSGLineItem( _
                    ByVal DeviceId As String,  _
                    ByVal Carrier As String,  _
                    ByVal Flight As String,  _
                    ByVal FlightDate As String,  _
                    ByVal Station As String,  _
                    ByVal UserId As String,  _
                    ByVal LineNumber As String,  _
                    ByVal LDPosition As String,  _
                    ByVal Commodity As String,  _
                    ByVal PieceCount As String,  _
                    ByVal SpecialWeight As String,  _
                    ByVal Destination As String,  _
                    ByVal FinalDestination As String,  _
                    ByVal DupFlag As String,  _
                    ByVal Container As String,  _
                    ByVal Remarks As String,  _
                    ByVal Weight As String,  _
                    ByVal ThruIndicator As String,  _
                    ByVal ActionIndicator As String,  _
                    ByVal Position As String) As String
            Dim results() As Object = Me.Invoke("WriteFDSGLineItem", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, UserId, LineNumber, LDPosition, Commodity, PieceCount, SpecialWeight, Destination, FinalDestination, DupFlag, Container, Remarks, Weight, ThruIndicator, ActionIndicator, Position})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginWriteFDSGLineItem( _
                    ByVal DeviceId As String,  _
                    ByVal Carrier As String,  _
                    ByVal Flight As String,  _
                    ByVal FlightDate As String,  _
                    ByVal Station As String,  _
                    ByVal UserId As String,  _
                    ByVal LineNumber As String,  _
                    ByVal LDPosition As String,  _
                    ByVal Commodity As String,  _
                    ByVal PieceCount As String,  _
                    ByVal SpecialWeight As String,  _
                    ByVal Destination As String,  _
                    ByVal FinalDestination As String,  _
                    ByVal DupFlag As String,  _
                    ByVal Container As String,  _
                    ByVal Remarks As String,  _
                    ByVal Weight As String,  _
                    ByVal ThruIndicator As String,  _
                    ByVal ActionIndicator As String,  _
                    ByVal Position As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("WriteFDSGLineItem", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, UserId, LineNumber, LDPosition, Commodity, PieceCount, SpecialWeight, Destination, FinalDestination, DupFlag, Container, Remarks, Weight, ThruIndicator, ActionIndicator, Position}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndWriteFDSGLineItem(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/AddRemarks", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function AddRemarks(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal BinNumber As String, ByVal DisplayFlag As String, ByVal PieceCount As String, ByVal Weight As String, ByVal Destination As String, ByVal Final As String, ByVal Remarks As String) As String
            Dim results() As Object = Me.Invoke("AddRemarks", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, BinNumber, DisplayFlag, PieceCount, Weight, Destination, Final, Remarks})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAddRemarks(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal BinNumber As String, ByVal DisplayFlag As String, ByVal PieceCount As String, ByVal Weight As String, ByVal Destination As String, ByVal Final As String, ByVal Remarks As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddRemarks", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, BinNumber, DisplayFlag, PieceCount, Weight, Destination, Final, Remarks}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAddRemarks(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetRemarks", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetRemarks(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String) As String
            Dim results() As Object = Me.Invoke("GetRemarks", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRemarks(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRemarks", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRemarks(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
