'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
'
Namespace NWA.Safetrac.Scanner.WebReferences.J2EE.DataSync
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DataSyncServiceBean", [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")>  _
    Partial Public Class DataSyncService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://10.145.86.152:9080/SafetracServicesWeb/services/DataSyncServiceSOAP"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function PerformGeneralService(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> ByVal GeneralServiceRequestElement As SafetracSOAPEnvelope) As <System.Xml.Serialization.XmlElementAttribute("GeneralServiceResponseElement", [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> SafetracSOAPEnvelope
            Dim results() As Object = Me.Invoke("PerformGeneralService", New Object() {GeneralServiceRequestElement})
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
        
        '''<remarks/>
        Public Function BeginPerformGeneralService(ByVal GeneralServiceRequestElement As SafetracSOAPEnvelope, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PerformGeneralService", New Object() {GeneralServiceRequestElement}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPerformGeneralService(ByVal asyncResult As System.IAsyncResult) As SafetracSOAPEnvelope
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function PerformDownloadService(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> ByVal DownloadServiceRequestElement As SafetracSOAPEnvelope) As <System.Xml.Serialization.XmlElementAttribute("DownloadServiceResponseElement", [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> SafetracSOAPEnvelope
            Dim results() As Object = Me.Invoke("PerformDownloadService", New Object() {DownloadServiceRequestElement})
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
        
        '''<remarks/>
        Public Function BeginPerformDownloadService(ByVal DownloadServiceRequestElement As SafetracSOAPEnvelope, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PerformDownloadService", New Object() {DownloadServiceRequestElement}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPerformDownloadService(ByVal asyncResult As System.IAsyncResult) As SafetracSOAPEnvelope
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function PerformUploadService(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> ByVal UploadServiceRequestElement As SafetracSOAPEnvelope) As <System.Xml.Serialization.XmlElementAttribute("UploadServiceResponseElement", [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")> SafetracSOAPEnvelope
            Dim results() As Object = Me.Invoke("PerformUploadService", New Object() {UploadServiceRequestElement})
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
        
        '''<remarks/>
        Public Function BeginPerformUploadService(ByVal UploadServiceRequestElement As SafetracSOAPEnvelope, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PerformUploadService", New Object() {UploadServiceRequestElement}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPerformUploadService(ByVal asyncResult As System.IAsyncResult) As SafetracSOAPEnvelope
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SafetracSOAPEnvelope)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")>  _
    Partial Public Class SafetracSOAPEnvelope
        
        Private headerField As MessageHeaderType
        
        Private bodyField As String
        
        Private loadStatusField As String
        
        Private returnCodeField As Integer
        
        Private errorCodeField As String
        
        Private errorMsgField As String
        
        '''<remarks/>
        Public Property header() As MessageHeaderType
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property body() As String
            Get
                Return Me.bodyField
            End Get
            Set
                Me.bodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property loadStatus() As String
            Get
                Return Me.loadStatusField
            End Get
            Set
                Me.loadStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property returnCode() As Integer
            Get
                Return Me.returnCodeField
            End Get
            Set
                Me.returnCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property errorMsg() As String
            Get
                Return Me.errorMsgField
            End Get
            Set
                Me.errorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")>  _
    Partial Public Class MessageHeaderType
        
        Private hhtIDField As String
        
        Private userIDField As String
        
        Private messageIDField As String
        
        Private deprStationCodeField As String
        
        Private isTrainingModeField As String
        
        Private serviceTypeField As MessageHeaderTypeServiceType
        
        Private requestedOperationTypeField As MessageHeaderTypeRequestedOperationType
        
        Public Sub New()
            MyBase.New
            Me.isTrainingModeField = "Y"
        End Sub
        
        '''<remarks/>
        Public Property hhtID() As String
            Get
                Return Me.hhtIDField
            End Get
            Set
                Me.hhtIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property userID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property messageID() As String
            Get
                Return Me.messageIDField
            End Get
            Set
                Me.messageIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property deprStationCode() As String
            Get
                Return Me.deprStationCodeField
            End Get
            Set
                Me.deprStationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isTrainingMode() As String
            Get
                Return Me.isTrainingModeField
            End Get
            Set
                Me.isTrainingModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property serviceType() As MessageHeaderTypeServiceType
            Get
                Return Me.serviceTypeField
            End Get
            Set
                Me.serviceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property requestedOperationType() As MessageHeaderTypeRequestedOperationType
            Get
                Return Me.requestedOperationTypeField
            End Get
            Set
                Me.requestedOperationTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")>  _
    Public Enum MessageHeaderTypeServiceType
        
        '''<remarks/>
        D
        
        '''<remarks/>
        U
        
        '''<remarks/>
        G
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://services.safetrac.nwa.com/DataSyncService/")>  _
    Public Enum MessageHeaderTypeRequestedOperationType
        
        '''<remarks/>
        MAIL
        
        '''<remarks/>
        ERRORCODES
        
        '''<remarks/>
        FLIGHT
        
        '''<remarks/>
        BAGS
        
        '''<remarks/>
        FREIGHT
        
        '''<remarks/>
        ULD
        
        '''<remarks/>
        ULDREG
        
        '''<remarks/>
        ULDDEF
        
        '''<remarks/>
        ULDCHECK
        
        '''<remarks/>
        ULDCREATE
        
        '''<remarks/>
        ULDPOS
        
        '''<remarks/>
        LINEITEM
        
        '''<remarks/>
        LDAPLOGIN
        
        '''<remarks/>
        REOPENCLOSEULD
        
        '''<remarks/>
        AIRCRAFTCONFIG
        
        '''<remarks/>
        PRECLOSE
        
        '''<remarks/>
        BAGTAGINQDUP
        
        '''<remarks/>
        BAGTAGINQ
        
        '''<remarks/>
        AWBINQ
        
        '''<remarks/>
        PASSENGERCONFIG
        
        '''<remarks/>
        VIEWBAGSTOGOINQ
        
        '''<remarks/>
        VIEWBINBULKINQ
        
        '''<remarks/>
        VIEWBAGSTOUNLOADINQ
        
        '''<remarks/>
        AIRLINECODE
        
        '''<remarks/>
        VIEWULDCARTINQ
        
        '''<remarks/>
        VIEWBAGSTOUNLD
    End Enum
End Namespace
