'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization
Imports NWA.Safetrac.Scanner.Utils


'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.832.
'
Namespace NWA.Safetrac.Scanner.WebReferences.NET.FlightLD
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_FlightLDSoap", [Namespace]:="http://safetrac.nwa.com/")>  _
    Partial Public Class WS_FlightLD
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = ConfigManager.WS_FlightLD_AOT
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/VerifyClock", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function VerifyClock(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ClockNumber As String) As String
            Dim results() As Object = Me.Invoke("VerifyClock", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ClockNumber})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginVerifyClock(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ClockNumber As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VerifyClock", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ClockNumber}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndVerifyClock(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/TDDLR", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function TDDLR(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String) As String
            Dim results() As Object = Me.Invoke("TDDLR", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginTDDLR(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal ArrivalDeparture As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TDDLR", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, ArrivalDeparture}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndTDDLR(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/GetLDResponse", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function GetLDResponse(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String) As String
            Dim results() As Object = Me.Invoke("GetLDResponse", New Object() {DeviceId, Carrier, Flight, FlightDate, Station})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetLDResponse(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLDResponse", New Object() {DeviceId, Carrier, Flight, FlightDate, Station}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetLDResponse(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://safetrac.nwa.com/FlightClose", RequestNamespace:="http://safetrac.nwa.com/", ResponseNamespace:="http://safetrac.nwa.com/")>  _
        Public Function FlightClose(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal Override As String, ByVal LineNumberList As String) As Object
            Dim results() As Object = Me.Invoke("FlightClose", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, Override, LineNumberList})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Function BeginFlightClose(ByVal DeviceId As String, ByVal Carrier As String, ByVal Flight As String, ByVal FlightDate As String, ByVal Station As String, ByVal Override As String, ByVal LineNumberList As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("FlightClose", New Object() {DeviceId, Carrier, Flight, FlightDate, Station, Override, LineNumberList}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndFlightClose(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
    End Class
End Namespace
